# SE-ResNet50 + 2-scale Bilinear + SAM + SWA — v3

Différences vs v1 et v2 :
- **2-scale bilinear** : layer3+layer4 seulement (vs v2 qui avait layer2+layer3+layer4 → layer2 ajoutait du bruit)
- **SAM + SWA** corrigé (vs v1 qui n'avait ni l'un ni l'autre)
- **Seed 123** : folds différents → plus de diversité pour l'ensemble
- **Rotation 90°** + GaussianBlur : augmentations plus adaptées aux textures
- **Patch only** : 300 epochs, patience 60
- Dest ensemble : v1_patch + v2_patch + v2_full + v3_patch → 4 modèles

## 1. Setup

In [1]:
from pathlib import Path
import random, time, math

import numpy as np
import pandas as pd
from PIL import Image

from sklearn.model_selection import StratifiedKFold

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.optim.swa_utils import AveragedModel
from torchvision import transforms
from tqdm.auto import tqdm

ROOT           = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
DATA_DIR       = ROOT / 'data'
OUTPUT_DIR     = ROOT / 'outputs'
CHECKPOINT_DIR = OUTPUT_DIR / 'checkpoints'
SUBMISSION_DIR = OUTPUT_DIR / 'submissions'

for p in [CHECKPOINT_DIR, SUBMISSION_DIR]:
    p.mkdir(parents=True, exist_ok=True)

SEED = 123
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.benchmark = True

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Root  :', ROOT)
print('Device:', DEVICE)
if torch.cuda.is_available():
    print('GPU   :', torch.cuda.get_device_name(0))
    print(f'VRAM  : {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB')

Root  : /home/onyxia/work/tilda-texture-classification
Device: cuda
GPU   : NVIDIA RTXA6000-48Q
VRAM  : 51.3 GB

## 2. Paramètres

In [2]:
N_SPLITS = 5
START_FOLD_PATCH = 1

NUM_CLASSES = 8
NUM_WORKERS = 0

PATCH_RESIZE  = (512, 768)
PATCH_SIZE    = 384

BATCH_SIZE_PATCH = 32

EPOCHS_PATCH  = 300
WARMUP_EPOCHS = 10

LR_PATCH        = 0.05
MOMENTUM        = 0.9
WEIGHT_DECAY    = 1e-3
LABEL_SMOOTHING = 0.1
PATIENCE        = 60

BILINEAR_REDUCTION = 64

MIXUP_ALPHA  = 0.4
CUTMIX_ALPHA = 1.0
CUTMIX_PROB  = 0.5

SWA_START_RATIO = 0.65
SAM_RHO         = 0.05

print('Config OK')
R = BILINEAR_REDUCTION
print(f'Features/echelle : {R*(R+1)//2}  |  Total FC input (2 echelles) : {2*R*(R+1)//2}')

Config OK
Features/echelle : 2080  |  Total FC input (2 echelles) : 4160

## 3. Données

In [3]:
def read_train_csv(path):
    try:
        df = pd.read_csv(path, sep=';')
        if len(df.columns) == 1:
            df = pd.read_csv(path)
    except Exception:
        df = pd.read_csv(path)
    df.columns = [c.strip() for c in df.columns]
    if 'id' not in df.columns or 'label' not in df.columns:
        raise ValueError(f'Colonnes attendues id,label. Trouvees: {df.columns.tolist()}')
    df['id'] = df['id'].astype(int)
    df['label'] = df['label'].astype(int)
    return df

def resolve_image_path(folder, image_id):
    stem = str(int(image_id))
    for ext in ['.tif', '.tiff', '.png', '.jpg']:
        p = folder / f'{stem}{ext}'
        if p.exists(): return p
    matches = sorted(folder.glob(f'{stem}.*'))
    if matches: return matches[0]
    raise FileNotFoundError(f'Image introuvable id={image_id}')

train_csv = DATA_DIR / 'train.csv'
train_dir = DATA_DIR / 'train'
test_dir  = DATA_DIR / 'test'

df = read_train_csv(train_csv)
df['path'] = df['id'].map(lambda x: resolve_image_path(train_dir, x))

test_paths = sorted(test_dir.glob('*.*'), key=lambda p: int(p.stem))
test_df = pd.DataFrame({'id': [int(p.stem) for p in test_paths], 'path': test_paths})

print(df.head())
print('\nDistribution:', df['label'].value_counts().sort_index().to_dict())
print(f'Train: {len(df)}  Test: {len(test_df)}')

   id  label                                               path
0   1      4  /home/onyxia/work/tilda-texture-classification...
1   2      6  /home/onyxia/work/tilda-texture-classification...
2   3      7  /home/onyxia/work/tilda-texture-classification...
3   4      6  /home/onyxia/work/tilda-texture-classification...
4   5      7  /home/onyxia/work/tilda-texture-classification...

Distribution: {0: 300, 1: 300, 2: 262, 3: 300, 4: 300, 5: 299, 6: 300, 7: 300}
Train: 2361  Test: 789

## 4. Transforms + Dataset

Augmentations clés :
- `RandomRotation(90)` : les textures sont invariantes à la rotation
- `GaussianBlur` : robustesse au flou → meilleure généralisation

In [4]:
patch_train_tfms = transforms.Compose([
    transforms.Resize(PATCH_RESIZE),
    transforms.RandomCrop((PATCH_SIZE, PATCH_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(degrees=90),
    transforms.GaussianBlur(kernel_size=5, sigma=(0.1, 1.5)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5]),
    transforms.RandomErasing(p=0.10, scale=(0.02, 0.06), ratio=(0.3, 3.3)),
])

patch_eval_full_tfms = transforms.Compose([
    transforms.Resize(PATCH_RESIZE),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5]),
])


class TildaDataset(Dataset):
    def __init__(self, frame, transform=None, has_labels=True):
        self.frame = frame.reset_index(drop=True).copy()
        self.transform = transform
        self.has_labels = has_labels

    def __len__(self): return len(self.frame)

    def __getitem__(self, idx):
        row = self.frame.iloc[idx]
        image = Image.open(row['path']).convert('L')
        if self.transform is not None:
            image = self.transform(image)
        label = int(row['label']) if self.has_labels else -1
        return image, label, int(row['id'])


def make_loader(frame, transform, batch_size, shuffle=False, has_labels=True):
    ds = TildaDataset(frame, transform=transform, has_labels=has_labels)
    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle,
                      num_workers=NUM_WORKERS, pin_memory=torch.cuda.is_available())

## 5. MixUp / CutMix

In [5]:
def rand_bbox(h, w, lam):
    cut_h = int(h * np.sqrt(1.0 - lam))
    cut_w = int(w * np.sqrt(1.0 - lam))
    cx, cy = np.random.randint(w), np.random.randint(h)
    x1, x2 = max(cx - cut_w // 2, 0), min(cx + cut_w // 2, w)
    y1, y2 = max(cy - cut_h // 2, 0), min(cy + cut_h // 2, h)
    return x1, y1, x2, y2


def mixup_cutmix(images, labels):
    B, C, H, W = images.shape
    idx = torch.randperm(B, device=images.device)
    if random.random() < CUTMIX_PROB:
        lam = float(np.random.beta(CUTMIX_ALPHA, CUTMIX_ALPHA))
        x1, y1, x2, y2 = rand_bbox(H, W, lam)
        images = images.clone()
        images[:, :, y1:y2, x1:x2] = images[idx, :, y1:y2, x1:x2]
        lam = 1.0 - (x2 - x1) * (y2 - y1) / (H * W)
    else:
        lam = float(np.random.beta(MIXUP_ALPHA, MIXUP_ALPHA))
        images = lam * images + (1.0 - lam) * images[idx]
    return images, labels, labels[idx], lam

print('MixUp/CutMix OK')

MixUp/CutMix OK

## 6. SAM Optimizer

In [6]:
class SAM(torch.optim.Optimizer):
    def __init__(self, params, base_optimizer, rho=0.05, **kwargs):
        assert rho >= 0.0
        defaults = dict(rho=rho, **kwargs)
        super().__init__(params, defaults)
        self.base_optimizer = base_optimizer(self.param_groups, **kwargs)
        self.param_groups   = self.base_optimizer.param_groups
        self.defaults.update(self.base_optimizer.defaults)

    @torch.no_grad()
    def first_step(self, zero_grad=False):
        grad_norm = self._grad_norm()
        for group in self.param_groups:
            scale = group['rho'] / (grad_norm + 1e-12)
            for p in group['params']:
                if p.grad is None: continue
                self.state[p]['old_p'] = p.data.clone()
                p.add_(p.grad * scale.to(p))
        if zero_grad: self.zero_grad()

    @torch.no_grad()
    def second_step(self, zero_grad=False):
        for group in self.param_groups:
            for p in group['params']:
                if p.grad is None: continue
                p.data = self.state[p]['old_p']
        self.base_optimizer.step()
        if zero_grad: self.zero_grad()

    def _grad_norm(self):
        dev = self.param_groups[0]['params'][0].device
        return torch.norm(torch.stack([
            p.grad.norm(p=2).to(dev)
            for group in self.param_groups
            for p in group['params'] if p.grad is not None
        ]), p=2)

    def load_state_dict(self, state_dict):
        super().load_state_dict(state_dict)
        self.base_optimizer.param_groups = self.param_groups

print('SAM OK')

SAM OK

## 7. Architecture — SE-ResNet50 + 2-scale Bilinear

- layer3 (1024ch) → bpool3 → 2080 features
- layer4 (2048ch) → bpool4 → 2080 features
- Concat → **4160 features** → Dropout(0.5) → FC(4160, 8)

Sans layer2 : features de plus haut niveau → meilleure généralisation

In [7]:
class SEBlock(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        hidden = max(channels // reduction, 4)
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(channels, hidden),
            nn.ReLU(inplace=True),
            nn.Linear(hidden, channels),
            nn.Sigmoid(),
        )

    def forward(self, x):
        b, c = x.shape[:2]
        w = self.pool(x).view(b, c)
        return x * self.fc(w).view(b, c, 1, 1)


class SEBottleneck(nn.Module):
    expansion = 4

    def __init__(self, in_planes, planes, stride=1, se_reduction=16):
        super().__init__()
        self.conv1 = nn.Conv2d(in_planes, planes, 1, bias=False)
        self.bn1   = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, 3, stride=stride, padding=1, bias=False)
        self.bn2   = nn.BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, planes * 4, 1, bias=False)
        self.bn3   = nn.BatchNorm2d(planes * 4)
        self.se    = SEBlock(planes * 4, reduction=se_reduction)
        self.shortcut = nn.Sequential()
        if stride != 1 or in_planes != planes * 4:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_planes, planes * 4, 1, stride=stride, bias=False),
                nn.BatchNorm2d(planes * 4),
            )

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)), inplace=True)
        out = F.relu(self.bn2(self.conv2(out)), inplace=True)
        out = self.se(self.bn3(self.conv3(out)))
        return F.relu(out + self.shortcut(x), inplace=True)


class BilinearPool(nn.Module):
    def __init__(self, in_channels, reduction=64):
        super().__init__()
        R = reduction
        self.reduce = nn.Sequential(
            nn.Conv2d(in_channels, R, 1, bias=False),
            nn.BatchNorm2d(R),
            nn.ReLU(inplace=True),
        )
        rows, cols = torch.triu_indices(R, R)
        self.register_buffer('triu_r', rows)
        self.register_buffer('triu_c', cols)
        self.out_features = R * (R + 1) // 2

    def forward(self, x):
        x = self.reduce(x)
        B, R, H, W = x.shape
        x = x.view(B, R, H * W)
        cov = torch.bmm(x, x.transpose(1, 2)) / (H * W)
        feat = cov[:, self.triu_r, self.triu_c]
        feat = torch.sign(feat) * torch.sqrt(torch.abs(feat) + 1e-10)
        return F.normalize(feat, dim=1)


class SEResNet50Bilinear2Scale(nn.Module):
    def __init__(self, num_classes=8, in_channels=1, reduction=64):
        super().__init__()
        self._in = 64
        self.stem = nn.Sequential(
            nn.Conv2d(in_channels, 64, 7, stride=2, padding=3, bias=False),
            nn.BatchNorm2d(64), nn.ReLU(inplace=True),
            nn.MaxPool2d(3, stride=2, padding=1),
        )
        self.layer1 = self._make(64,  3, stride=1)
        self.layer2 = self._make(128, 4, stride=2)
        self.layer3 = self._make(256, 6, stride=2)
        self.layer4 = self._make(512, 3, stride=2)

        self.bpool3 = BilinearPool(1024, reduction=reduction)
        self.bpool4 = BilinearPool(2048, reduction=reduction)

        feat_dim = 2 * reduction * (reduction + 1) // 2
        self.dropout = nn.Dropout(p=0.5)
        self.fc = nn.Linear(feat_dim, num_classes)

        self.apply(self._init_w)
        nn.init.xavier_normal_(self.fc.weight, gain=0.01)
        nn.init.zeros_(self.fc.bias)

    def _make(self, planes, n, stride=1):
        layers = []
        for s in [stride] + [1] * (n - 1):
            layers.append(SEBottleneck(self._in, planes, stride=s))
            self._in = planes * 4
        return nn.Sequential(*layers)

    def _init_w(self, m):
        if isinstance(m, nn.Conv2d):
            nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
        elif isinstance(m, nn.BatchNorm2d):
            nn.init.ones_(m.weight); nn.init.zeros_(m.bias)
        elif isinstance(m, nn.Linear):
            nn.init.xavier_normal_(m.weight)
            if m.bias is not None: nn.init.zeros_(m.bias)

    def forward(self, x):
        x  = self.stem(x)
        x  = self.layer1(x)
        x  = self.layer2(x)
        x3 = self.layer3(x)
        x4 = self.layer4(x3)
        f3 = self.bpool3(x3)
        f4 = self.bpool4(x4)
        return self.fc(self.dropout(torch.cat([f3, f4], dim=1)))


def seresnet50_bilinear_v3(num_classes=8):
    return SEResNet50Bilinear2Scale(num_classes=num_classes, in_channels=1,
                                    reduction=BILINEAR_REDUCTION)


m = seresnet50_bilinear_v3()
n_params = sum(p.numel() for p in m.parameters())
print(f'SE-ResNet50-Bilinear-2scale-v3 params: {n_params/1e6:.2f}M')
print(f'Feature dim FC: {2 * BILINEAR_REDUCTION * (BILINEAR_REDUCTION+1) // 2}')
del m

SE-ResNet50-Bilinear-2scale-v3 params: 26.26M
Feature dim FC: 4160

## 8. Eval + TTA 36 variants

In [8]:
@torch.no_grad()
def evaluate(model, loader, criterion):
    model.eval()
    total_loss, correct, n = 0.0, 0, 0
    y_true, y_pred = [], []
    for images, labels, _ in tqdm(loader, leave=False):
        images = images.to(DEVICE, non_blocking=True)
        labels = labels.to(DEVICE, non_blocking=True)
        logits = model(images)
        loss = criterion(logits, labels)
        total_loss += loss.item() * labels.size(0)
        preds = logits.argmax(1)
        correct += (preds == labels).sum().item()
        n += labels.size(0)
        y_true.extend(labels.cpu().numpy().tolist())
        y_pred.extend(preds.cpu().numpy().tolist())
    return correct / n, total_loss / n, np.array(y_true), np.array(y_pred)


def crop_grid(images, crop_size=384):
    _, _, h, w = images.shape
    top  = [0, max((h - crop_size) // 2, 0), max(h - crop_size, 0)]
    left = [0, max((w - crop_size) // 2, 0), max(w - crop_size, 0)]
    return [images[:, :, t:t+crop_size, l:l+crop_size]
            for t in top for l in left]


@torch.no_grad()
def predict_patch_tta36(model, loader, crop_size=384):
    model.eval()
    all_probs, all_ids = [], []
    for images, _, image_ids in tqdm(loader, leave=False):
        images = images.to(DEVICE, non_blocking=True)
        prob_list = []
        for crop in crop_grid(images, crop_size=crop_size):
            for v in [crop,
                      torch.flip(crop, dims=[-1]),
                      torch.flip(crop, dims=[-2]),
                      torch.flip(crop, dims=[-2, -1])]:
                prob_list.append(torch.softmax(model(v), dim=1))
        probs = torch.stack(prob_list).mean(0)
        all_probs.append(probs.cpu())
        all_ids.extend(image_ids.numpy().tolist())
    return torch.cat(all_probs).numpy(), np.array(all_ids)


def save_submission(ids, probs, path):
    sub = pd.DataFrame({'id': ids, 'label': probs.argmax(1).astype(int)}).sort_values('id')
    sub.to_csv(path, index=False)
    print('Saved:', path)
    print(sub['label'].value_counts().sort_index())
    return sub

print('Inference OK')

Inference OK

## 9. Entraînement SAM + SWA

In [9]:
def make_scheduler(optimizer, warmup_epochs, total_epochs, base_lr):
    min_lr = base_lr * 0.01
    def fn(epoch):
        if epoch < warmup_epochs:
            return (epoch + 1) / warmup_epochs
        progress = (epoch - warmup_epochs) / max(total_epochs - warmup_epochs, 1)
        cosine = 0.5 * (1.0 + math.cos(math.pi * progress))
        return min_lr / base_lr + (1.0 - min_lr / base_lr) * cosine
    return torch.optim.lr_scheduler.LambdaLR(optimizer, fn)


def train_one_epoch_sam(model, loader, criterion, optimizer):
    model.train()
    total_loss, correct, n = 0.0, 0, 0
    for images, labels, _ in tqdm(loader, leave=False):
        images = images.to(DEVICE, non_blocking=True)
        labels = labels.to(DEVICE, non_blocking=True)
        images_m, la, lb, lam = mixup_cutmix(images, labels)

        logits = model(images_m)
        loss   = lam * criterion(logits, la) + (1.0 - lam) * criterion(logits, lb)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.first_step(zero_grad=True)

        logits2 = model(images_m)
        loss2   = lam * criterion(logits2, la) + (1.0 - lam) * criterion(logits2, lb)
        loss2.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.second_step(zero_grad=True)

        total_loss += loss.item() * labels.size(0)
        correct    += (logits.detach().argmax(1) == la).sum().item()
        n          += labels.size(0)
    return correct / n, total_loss / n


def update_bn_swa(swa_model, loader):
    swa_model.train()
    for m in swa_model.modules():
        if isinstance(m, nn.BatchNorm2d):
            m.reset_running_stats()
            m.momentum = None
    with torch.no_grad():
        for images, _, _ in tqdm(loader, desc='SWA BN', leave=False):
            swa_model(images.to(DEVICE))
    for m in swa_model.modules():
        if isinstance(m, nn.BatchNorm2d):
            m.momentum = 0.1
    swa_model.eval()


def fit_fold(model, train_loader, val_loader, run_name, epochs, lr):
    criterion = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTHING)
    optimizer = SAM(model.parameters(), torch.optim.SGD, rho=SAM_RHO,
                    lr=lr, momentum=MOMENTUM, weight_decay=WEIGHT_DECAY, nesterov=True)
    scheduler = make_scheduler(optimizer.base_optimizer, WARMUP_EPOCHS, epochs, lr)

    swa_model = AveragedModel(model)
    swa_start = max(int(SWA_START_RATIO * epochs), 30)
    swa_n     = 0

    best_acc   = -1.0
    best_epoch = 0
    best_path  = CHECKPOINT_DIR / f'best_{run_name}.pt'
    history    = []
    t0         = time.time()

    for epoch in range(1, epochs + 1):
        train_acc, train_loss = train_one_epoch_sam(model, train_loader, criterion, optimizer)
        val_acc, val_loss, _, _ = evaluate(model, val_loader, criterion)
        scheduler.step()

        if epoch >= swa_start:
            swa_model.update_parameters(model)
            swa_n += 1

        if val_acc > best_acc:
            best_acc, best_epoch = val_acc, epoch
            torch.save({'epoch': epoch, 'model_state_dict': model.state_dict(),
                        'best_acc': best_acc}, best_path)

        history.append({'epoch': epoch, 'train_acc': train_acc, 'train_loss': train_loss,
                        'val_acc': val_acc, 'val_loss': val_loss,
                        'lr': scheduler.get_last_lr()[0]})

        print(f'{run_name} | ep {epoch:03d} | train {train_acc:.4f}/{train_loss:.4f} | '
              f'val {val_acc:.4f}/{val_loss:.4f} | best {best_acc:.4f} @ {best_epoch}')

        if epoch - best_epoch >= PATIENCE:
            print(f'Early stop: {PATIENCE} epochs sans amelioration')
            break

    if swa_n >= 5:
        update_bn_swa(swa_model, train_loader)
        swa_val_acc, _, _, _ = evaluate(swa_model, val_loader, criterion)
        print(f'SWA ({swa_n} snapshots) val acc: {swa_val_acc:.4f}  |  best ckpt: {best_acc:.4f}')
        if swa_val_acc >= best_acc:
            best_acc = swa_val_acc
            swa_sd = {k[len('module.'):]: v
                      for k, v in swa_model.state_dict().items()
                      if k.startswith('module.')}
            torch.save({'epoch': epoch, 'model_state_dict': swa_sd,
                        'best_acc': best_acc, 'is_swa': True}, best_path)
            print('-> SWA model saved as best')
        else:
            ckpt = torch.load(best_path, map_location=DEVICE, weights_only=True)
            model.load_state_dict(ckpt['model_state_dict'])
            print('-> Keeping best checkpoint')

    elapsed = (time.time() - t0) / 60
    return pd.DataFrame(history), best_path, best_acc, best_epoch, elapsed

print('fit_fold OK')

fit_fold OK

## 10. Boucle 5-fold patch

In [10]:
def run_5fold_patch(experiment_name, model_factory, start_fold=1):
    skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)
    fold_probs   = []
    ids_ref      = None
    fold_results = []

    test_loader = make_loader(test_df, patch_eval_full_tfms, batch_size=BATCH_SIZE_PATCH,
                              shuffle=False, has_labels=False)

    for fold, (tr_idx, va_idx) in enumerate(skf.split(df, df['label']), start=1):
        fold_name  = f'{experiment_name}_fold{fold}'
        probs_path = CHECKPOINT_DIR / f'probs_{fold_name}.npy'
        ids_path   = CHECKPOINT_DIR / f'ids_{fold_name}.npy'

        if fold < start_fold:
            if probs_path.exists() and ids_path.exists():
                probs = np.load(probs_path)
                ids   = np.load(ids_path)
                fold_probs.append(probs)
                ids_ref = ids if ids_ref is None else ids_ref
                print(f'Fold {fold}: loaded saved probs {probs.shape}')
            else:
                print(f'Fold {fold}: skipped (no saved probs found)')
            continue

        print('\n' + '='*80)
        print(f'{experiment_name} | fold {fold}/{N_SPLITS}')
        print('='*80)

        tr_df = df.iloc[tr_idx].reset_index(drop=True)
        va_df = df.iloc[va_idx].reset_index(drop=True)
        train_loader = make_loader(tr_df, patch_train_tfms, BATCH_SIZE_PATCH, shuffle=True)
        val_loader   = make_loader(va_df, patch_eval_full_tfms, BATCH_SIZE_PATCH, shuffle=False)

        model = model_factory().to(DEVICE)
        hist_df, best_path, best_acc, best_epoch, elapsed = \
            fit_fold(model, train_loader, val_loader, fold_name, EPOCHS_PATCH, LR_PATCH)
        hist_df.to_csv(OUTPUT_DIR / f'history_{fold_name}.csv', index=False)

        ckpt = torch.load(best_path, map_location=DEVICE, weights_only=True)
        model.load_state_dict(ckpt['model_state_dict'])

        probs, ids = predict_patch_tta36(model, test_loader, crop_size=PATCH_SIZE)
        np.save(probs_path, probs)
        np.save(ids_path,   ids)
        if ids_ref is None:
            ids_ref = ids
        else:
            assert np.array_equal(ids_ref, ids), 'Test ids differents entre folds!'

        fold_probs.append(probs)
        save_submission(ids, probs,
                        SUBMISSION_DIR / f'submission_{fold_name}_tta_labels0.csv')

        fold_results.append({
            'fold': fold, 'best_val_acc': best_acc,
            'best_epoch': best_epoch, 'training_time_min': elapsed,
        })

        del model
        torch.cuda.empty_cache()

    results_df = pd.DataFrame(fold_results)
    results_df.to_csv(OUTPUT_DIR / f'results_{experiment_name}.csv', index=False)

    if len(fold_probs) == N_SPLITS:
        mean_probs = np.mean(fold_probs, axis=0)
        np.save(CHECKPOINT_DIR / f'probs_{experiment_name}_5fold.npy', mean_probs)
        np.save(CHECKPOINT_DIR / f'ids_{experiment_name}_5fold.npy',   ids_ref)
        save_submission(ids_ref, mean_probs,
                        SUBMISSION_DIR / f'submission_{experiment_name}_5fold_tta_labels0.csv')
    else:
        print(f'Pas de CSV 5-fold final : {len(fold_probs)}/{N_SPLITS} folds OK')

    display(results_df)
    if not results_df.empty:
        print(f"Mean val acc: {results_df['best_val_acc'].mean():.4f} "
              f"+/- {results_df['best_val_acc'].std():.4f}")
    return results_df

print('run_5fold_patch OK')

run_5fold_patch OK

## 11. Run A — Patch 384×384 (300 epochs, seed=123)

In [11]:
patch_results = run_5fold_patch(
    experiment_name = 'seresnet50_bilinear_v3_patch',
    model_factory   = seresnet50_bilinear_v3,
    start_fold      = START_FOLD_PATCH,
)

================================================================================
seresnet50_bilinear_v3_patch | fold 1/5
================================================================================

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 001 | train 0.1229/2.0800 | val 0.1332/2.0785 | best 0.1332 @ 1

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 002 | train 0.1250/2.0796 | val 0.1501/2.0777 | best 0.1501 @ 2

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 003 | train 0.1176/2.0799 | val 0.1586/2.0764 | best 0.1586 @ 3

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 004 | train 0.1319/2.0784 | val 0.1522/2.0729 | best 0.1586 @ 3

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 005 | train 0.1525/2.0739 | val 0.1734/2.0677 | best 0.1734 @ 5

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 006 | train 0.1504/2.0634 | val 0.1839/2.0453 | best 0.1839 @ 6

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 007 | train 0.1721/2.0413 | val 0.1860/2.0306 | best 0.1860 @ 7

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 008 | train 0.1727/2.0304 | val 0.1839/1.9921 | best 0.1860 @ 7

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 009 | train 0.1976/2.0133 | val 0.1987/1.9816 | best 0.1987 @ 9

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 010 | train 0.1838/2.0048 | val 0.2008/1.9615 | best 0.2008 @ 10

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 011 | train 0.1992/1.9978 | val 0.2643/1.9437 | best 0.2643 @ 11

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 012 | train 0.1976/1.9895 | val 0.2368/1.9379 | best 0.2643 @ 11

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 013 | train 0.1907/1.9772 | val 0.2495/1.9429 | best 0.2643 @ 11

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 014 | train 0.1960/1.9662 | val 0.1966/1.9208 | best 0.2643 @ 11

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 015 | train 0.2066/1.9762 | val 0.1860/1.9186 | best 0.2643 @ 11

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 016 | train 0.2150/1.9699 | val 0.2558/1.9468 | best 0.2643 @ 11

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 017 | train 0.2172/1.9442 | val 0.2643/1.8588 | best 0.2643 @ 11

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 018 | train 0.2161/1.9558 | val 0.3023/1.8817 | best 0.3023 @ 18

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 019 | train 0.2214/1.9564 | val 0.3340/1.8595 | best 0.3340 @ 19

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 020 | train 0.2060/1.9377 | val 0.2875/1.8610 | best 0.3340 @ 19

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 021 | train 0.2230/1.9458 | val 0.3192/1.8412 | best 0.3340 @ 19

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 022 | train 0.2315/1.9377 | val 0.2939/1.8458 | best 0.3340 @ 19

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 023 | train 0.2293/1.9258 | val 0.3087/1.8636 | best 0.3340 @ 19

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 024 | train 0.2415/1.9383 | val 0.2896/1.8778 | best 0.3340 @ 19

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 025 | train 0.2357/1.9239 | val 0.4123/1.7782 | best 0.4123 @ 25

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 026 | train 0.2325/1.9132 | val 0.3023/1.8498 | best 0.4123 @ 25

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 027 | train 0.2574/1.9225 | val 0.3784/1.7973 | best 0.4123 @ 25

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 028 | train 0.2617/1.9111 | val 0.3911/1.7661 | best 0.4123 @ 25

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 029 | train 0.2516/1.9130 | val 0.3129/1.8320 | best 0.4123 @ 25

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 030 | train 0.2956/1.8994 | val 0.4207/1.7702 | best 0.4207 @ 30

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 031 | train 0.2791/1.8793 | val 0.4123/1.7383 | best 0.4207 @ 30

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 032 | train 0.2452/1.8991 | val 0.3319/1.7869 | best 0.4207 @ 30

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 033 | train 0.2500/1.8866 | val 0.3615/1.7856 | best 0.4207 @ 30

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 034 | train 0.2585/1.8909 | val 0.3805/1.7503 | best 0.4207 @ 30

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 035 | train 0.2474/1.8823 | val 0.3996/1.7269 | best 0.4207 @ 30

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 036 | train 0.2754/1.8732 | val 0.3869/1.7379 | best 0.4207 @ 30

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 037 | train 0.2717/1.8707 | val 0.3256/1.8021 | best 0.4207 @ 30

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 038 | train 0.2717/1.8838 | val 0.4461/1.7222 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 039 | train 0.2754/1.8806 | val 0.3890/1.7170 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 040 | train 0.2802/1.8569 | val 0.3848/1.7684 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 041 | train 0.2585/1.8703 | val 0.4440/1.6879 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 042 | train 0.2495/1.9074 | val 0.4144/1.6991 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 043 | train 0.2638/1.8929 | val 0.4313/1.7305 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 044 | train 0.2860/1.8680 | val 0.3700/1.7612 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 045 | train 0.2770/1.8792 | val 0.3679/1.6999 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 046 | train 0.2474/1.8786 | val 0.3552/1.7765 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 047 | train 0.3014/1.8564 | val 0.4038/1.6937 | best 0.4461 @ 38

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 048 | train 0.2913/1.8515 | val 0.4567/1.6642 | best 0.4567 @ 48

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 049 | train 0.2844/1.8751 | val 0.3679/1.7397 | best 0.4567 @ 48

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 050 | train 0.2797/1.8516 | val 0.3488/1.7529 | best 0.4567 @ 48

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 051 | train 0.2749/1.8766 | val 0.2960/1.8648 | best 0.4567 @ 48

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 052 | train 0.2569/1.8604 | val 0.4292/1.6872 | best 0.4567 @ 48

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 053 | train 0.2691/1.8342 | val 0.4355/1.7014 | best 0.4567 @ 48

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 054 | train 0.2511/1.8696 | val 0.3636/1.7550 | best 0.4567 @ 48

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 055 | train 0.3083/1.8169 | val 0.4884/1.6692 | best 0.4884 @ 55

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 056 | train 0.2971/1.8109 | val 0.4334/1.6765 | best 0.4884 @ 55

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 057 | train 0.3072/1.8698 | val 0.3784/1.7517 | best 0.4884 @ 55

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 058 | train 0.2744/1.8634 | val 0.4228/1.6910 | best 0.4884 @ 55

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 059 | train 0.2797/1.8793 | val 0.4165/1.7130 | best 0.4884 @ 55

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 060 | train 0.2908/1.8380 | val 0.4672/1.6547 | best 0.4884 @ 55

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 061 | train 0.2421/1.8714 | val 0.4334/1.7100 | best 0.4884 @ 55

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 062 | train 0.3056/1.8445 | val 0.5011/1.6347 | best 0.5011 @ 62

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 063 | train 0.3035/1.8186 | val 0.4503/1.6563 | best 0.5011 @ 62

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 064 | train 0.2574/1.8806 | val 0.5095/1.6100 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 065 | train 0.2918/1.8450 | val 0.3658/1.7846 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 066 | train 0.3040/1.8116 | val 0.4186/1.6610 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 067 | train 0.3189/1.7904 | val 0.4524/1.6302 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 068 | train 0.2675/1.8822 | val 0.4059/1.6994 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 069 | train 0.2839/1.8632 | val 0.3805/1.7160 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 070 | train 0.2754/1.8141 | val 0.4334/1.6586 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 071 | train 0.3046/1.7903 | val 0.4715/1.6275 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 072 | train 0.2881/1.8278 | val 0.3953/1.6982 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 073 | train 0.3120/1.8281 | val 0.4799/1.6114 | best 0.5095 @ 64

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 074 | train 0.2881/1.8112 | val 0.5264/1.5851 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 075 | train 0.2812/1.8240 | val 0.5116/1.6276 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 076 | train 0.2966/1.8249 | val 0.4609/1.6262 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 077 | train 0.2876/1.8212 | val 0.3975/1.7005 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 078 | train 0.3051/1.8222 | val 0.5201/1.5840 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 079 | train 0.3008/1.8042 | val 0.4757/1.5968 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 080 | train 0.2855/1.7993 | val 0.4693/1.6406 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 081 | train 0.2791/1.8639 | val 0.3932/1.7269 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 082 | train 0.2987/1.8149 | val 0.4736/1.6203 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 083 | train 0.2903/1.7973 | val 0.5011/1.5691 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 084 | train 0.2950/1.8252 | val 0.4207/1.6989 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 085 | train 0.3109/1.8041 | val 0.3869/1.7099 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 086 | train 0.3130/1.8017 | val 0.5116/1.5920 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 087 | train 0.3220/1.8160 | val 0.4630/1.5889 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 088 | train 0.2797/1.8107 | val 0.4419/1.6426 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 089 | train 0.3099/1.8017 | val 0.4440/1.6253 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 090 | train 0.3130/1.8050 | val 0.3129/1.8341 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 091 | train 0.3003/1.8168 | val 0.5095/1.5805 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 092 | train 0.3226/1.7895 | val 0.5032/1.5784 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 093 | train 0.3236/1.8008 | val 0.3615/1.7523 | best 0.5264 @ 74

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 094 | train 0.3189/1.7941 | val 0.5349/1.5289 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 095 | train 0.3411/1.7852 | val 0.4884/1.5880 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 096 | train 0.3453/1.7837 | val 0.4715/1.6247 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 097 | train 0.3464/1.7625 | val 0.4228/1.6491 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 098 | train 0.3167/1.8322 | val 0.3827/1.7524 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 099 | train 0.3215/1.7472 | val 0.4799/1.5765 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 100 | train 0.3178/1.7883 | val 0.4693/1.6050 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 101 | train 0.3480/1.7856 | val 0.4672/1.6459 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 102 | train 0.2971/1.8084 | val 0.5053/1.5696 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 103 | train 0.3263/1.7962 | val 0.5201/1.5515 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 104 | train 0.3268/1.7528 | val 0.5307/1.5545 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 105 | train 0.3490/1.7773 | val 0.5201/1.5455 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 106 | train 0.3326/1.7893 | val 0.4482/1.6524 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 107 | train 0.3284/1.7792 | val 0.5053/1.6223 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 108 | train 0.3003/1.7677 | val 0.5116/1.5841 | best 0.5349 @ 94

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 109 | train 0.3268/1.7400 | val 0.5497/1.5260 | best 0.5497 @ 109

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 110 | train 0.3136/1.8101 | val 0.5433/1.5850 | best 0.5497 @ 109

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 111 | train 0.3067/1.8037 | val 0.4651/1.6213 | best 0.5497 @ 109

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 112 | train 0.3671/1.7150 | val 0.4609/1.6130 | best 0.5497 @ 109

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 113 | train 0.3379/1.7634 | val 0.4905/1.5755 | best 0.5497 @ 109

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 114 | train 0.3432/1.7658 | val 0.4736/1.6059 | best 0.5497 @ 109

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 115 | train 0.3480/1.7801 | val 0.3679/1.8052 | best 0.5497 @ 109

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 116 | train 0.3480/1.6975 | val 0.5476/1.4953 | best 0.5497 @ 109

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 117 | train 0.3702/1.7620 | val 0.4651/1.6437 | best 0.5497 @ 109

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 118 | train 0.3438/1.7622 | val 0.5687/1.5009 | best 0.5687 @ 118

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 119 | train 0.3210/1.7580 | val 0.4820/1.5894 | best 0.5687 @ 118

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 120 | train 0.3475/1.7679 | val 0.5032/1.5928 | best 0.5687 @ 118

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 121 | train 0.3157/1.7918 | val 0.4884/1.5523 | best 0.5687 @ 118

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 122 | train 0.3490/1.7368 | val 0.5455/1.4780 | best 0.5687 @ 118

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 123 | train 0.3199/1.8020 | val 0.4123/1.7412 | best 0.5687 @ 118

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 124 | train 0.3697/1.7654 | val 0.4313/1.6649 | best 0.5687 @ 118

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 125 | train 0.3506/1.7476 | val 0.5349/1.5383 | best 0.5687 @ 118

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 126 | train 0.3416/1.7505 | val 0.5666/1.5255 | best 0.5687 @ 118

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 127 | train 0.3914/1.7234 | val 0.5856/1.4949 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 128 | train 0.3464/1.7431 | val 0.5560/1.5359 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 129 | train 0.3395/1.7772 | val 0.5476/1.5064 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 130 | train 0.3745/1.7504 | val 0.4545/1.6640 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 131 | train 0.3596/1.7030 | val 0.4778/1.6136 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 132 | train 0.3263/1.7146 | val 0.5307/1.4876 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 133 | train 0.3141/1.7321 | val 0.5116/1.5841 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 134 | train 0.3210/1.7304 | val 0.5687/1.5123 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 135 | train 0.3300/1.7084 | val 0.5328/1.5231 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 136 | train 0.3506/1.7310 | val 0.4672/1.5405 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 137 | train 0.3586/1.6910 | val 0.5053/1.5068 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 138 | train 0.3475/1.7495 | val 0.5729/1.4564 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 139 | train 0.3353/1.7473 | val 0.5666/1.4495 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 140 | train 0.3575/1.7022 | val 0.5074/1.5514 | best 0.5856 @ 127

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 141 | train 0.3750/1.7179 | val 0.5962/1.4327 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 142 | train 0.3644/1.6977 | val 0.5666/1.4728 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 143 | train 0.3475/1.7028 | val 0.5391/1.5489 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 144 | train 0.3633/1.7570 | val 0.5645/1.4968 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 145 | train 0.3829/1.7050 | val 0.5666/1.4864 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 146 | train 0.3522/1.7356 | val 0.5433/1.5435 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 147 | train 0.3167/1.7105 | val 0.5856/1.4707 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 148 | train 0.3326/1.7134 | val 0.5032/1.5955 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 149 | train 0.3686/1.7117 | val 0.5518/1.5168 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 150 | train 0.3443/1.6739 | val 0.5370/1.5133 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 151 | train 0.3342/1.6731 | val 0.5032/1.5404 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 152 | train 0.3660/1.7478 | val 0.5793/1.4464 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 153 | train 0.3501/1.7332 | val 0.4123/1.6839 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 154 | train 0.3697/1.6982 | val 0.4397/1.6209 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 155 | train 0.3543/1.7067 | val 0.5708/1.4415 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 156 | train 0.3543/1.6845 | val 0.5328/1.5357 | best 0.5962 @ 141

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 157 | train 0.3649/1.6836 | val 0.5983/1.4365 | best 0.5983 @ 157

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 158 | train 0.3618/1.7141 | val 0.5941/1.4308 | best 0.5983 @ 157

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 159 | train 0.3718/1.6625 | val 0.6195/1.4017 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 160 | train 0.3925/1.7211 | val 0.4419/1.6232 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 161 | train 0.3522/1.7173 | val 0.4989/1.5885 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 162 | train 0.3655/1.6718 | val 0.5032/1.5506 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 163 | train 0.3676/1.7093 | val 0.5455/1.4808 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 164 | train 0.3480/1.7250 | val 0.4947/1.5738 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 165 | train 0.3543/1.7405 | val 0.4482/1.6382 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 166 | train 0.4010/1.6663 | val 0.4334/1.6090 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 167 | train 0.3904/1.6441 | val 0.6173/1.3871 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 168 | train 0.3782/1.6735 | val 0.4630/1.6326 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 169 | train 0.3708/1.6814 | val 0.6110/1.4442 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 170 | train 0.3480/1.7030 | val 0.3615/1.8235 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 171 | train 0.3776/1.7061 | val 0.5856/1.3970 | best 0.6195 @ 159

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 172 | train 0.4057/1.6128 | val 0.6279/1.3714 | best 0.6279 @ 172

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 173 | train 0.4041/1.6571 | val 0.5455/1.4695 | best 0.6279 @ 172

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 174 | train 0.3649/1.6423 | val 0.6173/1.3994 | best 0.6279 @ 172

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 175 | train 0.3713/1.6588 | val 0.6575/1.3271 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 176 | train 0.4174/1.6298 | val 0.5920/1.4371 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 177 | train 0.3639/1.7114 | val 0.5793/1.4424 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 178 | train 0.3443/1.7007 | val 0.6047/1.4215 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 179 | train 0.3893/1.6695 | val 0.4567/1.6131 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 180 | train 0.3867/1.6587 | val 0.6554/1.3332 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 181 | train 0.3750/1.6920 | val 0.6110/1.3899 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 182 | train 0.3829/1.6901 | val 0.5433/1.4964 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 183 | train 0.4137/1.6611 | val 0.5201/1.5516 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 184 | train 0.3771/1.6711 | val 0.6216/1.3986 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 185 | train 0.3814/1.6545 | val 0.4820/1.6357 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 186 | train 0.3702/1.6596 | val 0.5370/1.5061 | best 0.6575 @ 175

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 187 | train 0.4311/1.6406 | val 0.6977/1.2954 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 188 | train 0.3506/1.6756 | val 0.6110/1.3997 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 189 | train 0.4041/1.6600 | val 0.6131/1.3915 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 190 | train 0.4396/1.6254 | val 0.6512/1.3091 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 191 | train 0.3888/1.6424 | val 0.6258/1.3748 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 192 | train 0.4110/1.5941 | val 0.6871/1.2930 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 193 | train 0.4041/1.6076 | val 0.5941/1.4149 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 194 | train 0.3798/1.6568 | val 0.6173/1.3976 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 195 | train 0.3951/1.6012 | val 0.6258/1.3263 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 196 | train 0.4100/1.5751 | val 0.6913/1.2705 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 197 | train 0.4343/1.6105 | val 0.6786/1.2705 | best 0.6977 @ 187

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 198 | train 0.4062/1.6418 | val 0.7357/1.2373 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 199 | train 0.4179/1.6159 | val 0.6808/1.2714 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 200 | train 0.4386/1.5730 | val 0.4524/1.7024 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 201 | train 0.4248/1.6240 | val 0.6871/1.2883 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 202 | train 0.3941/1.6199 | val 0.6406/1.2981 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 203 | train 0.4280/1.5890 | val 0.6660/1.3023 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 204 | train 0.3946/1.6388 | val 0.5877/1.3812 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 205 | train 0.4153/1.6360 | val 0.6131/1.3721 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 206 | train 0.4025/1.6094 | val 0.5539/1.4479 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 207 | train 0.4206/1.6206 | val 0.7082/1.2677 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 208 | train 0.4084/1.6160 | val 0.7146/1.2785 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 209 | train 0.3957/1.6067 | val 0.7167/1.2311 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 210 | train 0.3750/1.6112 | val 0.6617/1.2872 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 211 | train 0.4264/1.6276 | val 0.6216/1.3699 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 212 | train 0.4258/1.5654 | val 0.7146/1.2477 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 213 | train 0.3978/1.6248 | val 0.7252/1.2336 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 214 | train 0.4100/1.6057 | val 0.6808/1.2873 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 215 | train 0.4349/1.5880 | val 0.6850/1.2815 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 216 | train 0.3867/1.6661 | val 0.6660/1.2650 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 217 | train 0.4089/1.6122 | val 0.6258/1.3588 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 218 | train 0.4004/1.5819 | val 0.6638/1.2833 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 219 | train 0.4248/1.6288 | val 0.5941/1.4044 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 220 | train 0.4179/1.5779 | val 0.5729/1.4032 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 221 | train 0.3861/1.5716 | val 0.6575/1.2666 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 222 | train 0.3972/1.5997 | val 0.7167/1.2422 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 223 | train 0.3644/1.5678 | val 0.7146/1.2348 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 224 | train 0.4439/1.5623 | val 0.6892/1.2990 | best 0.7357 @ 198

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 225 | train 0.4502/1.5780 | val 0.7548/1.1848 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 226 | train 0.3692/1.6086 | val 0.5772/1.4620 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 227 | train 0.3935/1.6472 | val 0.6786/1.2772 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 228 | train 0.4502/1.5645 | val 0.7294/1.2088 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 229 | train 0.4025/1.5410 | val 0.6681/1.2811 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 230 | train 0.4179/1.5497 | val 0.7357/1.1974 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 231 | train 0.3898/1.6121 | val 0.7167/1.2557 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 232 | train 0.4693/1.5912 | val 0.7421/1.1778 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 233 | train 0.4163/1.5744 | val 0.7167/1.2076 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 234 | train 0.4380/1.5797 | val 0.6660/1.2444 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 235 | train 0.4359/1.5630 | val 0.7505/1.1957 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 236 | train 0.4465/1.5722 | val 0.6681/1.2602 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 237 | train 0.4582/1.5568 | val 0.6871/1.2228 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 238 | train 0.5228/1.5270 | val 0.7400/1.1982 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 239 | train 0.3898/1.5269 | val 0.6554/1.2611 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 240 | train 0.4364/1.5313 | val 0.7209/1.2333 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 241 | train 0.4423/1.5617 | val 0.7230/1.1964 | best 0.7548 @ 225

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 242 | train 0.4349/1.5563 | val 0.7717/1.1560 | best 0.7717 @ 242

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 243 | train 0.4693/1.5304 | val 0.7400/1.1657 | best 0.7717 @ 242

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 244 | train 0.4571/1.4743 | val 0.7505/1.1674 | best 0.7717 @ 242

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 245 | train 0.4221/1.4964 | val 0.7886/1.1183 | best 0.7886 @ 245

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 246 | train 0.4062/1.5769 | val 0.7082/1.2569 | best 0.7886 @ 245

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 247 | train 0.4719/1.5055 | val 0.7907/1.1405 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 248 | train 0.4756/1.5187 | val 0.6913/1.2594 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 249 | train 0.3999/1.5895 | val 0.7188/1.1998 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 250 | train 0.4269/1.5351 | val 0.7188/1.1851 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 251 | train 0.4311/1.5688 | val 0.7019/1.2514 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 252 | train 0.4248/1.5125 | val 0.6998/1.2424 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 253 | train 0.5090/1.4984 | val 0.7696/1.1289 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 254 | train 0.4592/1.5531 | val 0.6448/1.3002 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 255 | train 0.4883/1.4826 | val 0.7674/1.1242 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 256 | train 0.4333/1.5517 | val 0.7674/1.1614 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 257 | train 0.4110/1.5012 | val 0.7357/1.1716 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 258 | train 0.4550/1.4835 | val 0.7674/1.1267 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 259 | train 0.4529/1.5207 | val 0.7040/1.2135 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 260 | train 0.4931/1.5083 | val 0.7125/1.1802 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 261 | train 0.4772/1.4717 | val 0.7632/1.1212 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 262 | train 0.5048/1.4727 | val 0.7886/1.1388 | best 0.7907 @ 247

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 263 | train 0.4958/1.5124 | val 0.8013/1.1046 | best 0.8013 @ 263

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 264 | train 0.4841/1.4880 | val 0.8076/1.1026 | best 0.8076 @ 264

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 265 | train 0.4868/1.4467 | val 0.8076/1.0859 | best 0.8076 @ 264

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 266 | train 0.4322/1.5168 | val 0.7844/1.1111 | best 0.8076 @ 264

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 267 | train 0.4386/1.5070 | val 0.7548/1.1420 | best 0.8076 @ 264

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 268 | train 0.3967/1.5372 | val 0.8224/1.0806 | best 0.8224 @ 268

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 269 | train 0.5132/1.4644 | val 0.8161/1.0708 | best 0.8224 @ 268

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 270 | train 0.4375/1.4902 | val 0.8182/1.0778 | best 0.8224 @ 268

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 271 | train 0.4899/1.5355 | val 0.7907/1.1041 | best 0.8224 @ 268

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 272 | train 0.4857/1.4570 | val 0.8013/1.1018 | best 0.8224 @ 268

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 273 | train 0.4513/1.4881 | val 0.7886/1.1292 | best 0.8224 @ 268

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 274 | train 0.4476/1.4966 | val 0.7886/1.0967 | best 0.8224 @ 268

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 275 | train 0.4338/1.5412 | val 0.8330/1.0987 | best 0.8330 @ 275

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 276 | train 0.4820/1.4580 | val 0.7696/1.1256 | best 0.8330 @ 275

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 277 | train 0.4407/1.4784 | val 0.8266/1.0709 | best 0.8330 @ 275

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 278 | train 0.5058/1.4588 | val 0.8013/1.0752 | best 0.8330 @ 275

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 279 | train 0.4311/1.4832 | val 0.8245/1.0776 | best 0.8330 @ 275

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 280 | train 0.4190/1.5323 | val 0.8055/1.0781 | best 0.8330 @ 275

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 281 | train 0.4640/1.4445 | val 0.7886/1.1108 | best 0.8330 @ 275

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 282 | train 0.4401/1.4881 | val 0.8182/1.0751 | best 0.8330 @ 275

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 283 | train 0.4465/1.4610 | val 0.8351/1.0533 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 284 | train 0.5122/1.4728 | val 0.8224/1.0847 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 285 | train 0.5614/1.4839 | val 0.7505/1.1514 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 286 | train 0.4650/1.4091 | val 0.8076/1.0780 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 287 | train 0.4317/1.4755 | val 0.7992/1.0722 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 288 | train 0.4650/1.4540 | val 0.8351/1.0463 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 289 | train 0.4460/1.5109 | val 0.7992/1.1102 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 290 | train 0.4682/1.4064 | val 0.7844/1.1155 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 291 | train 0.4740/1.5435 | val 0.7674/1.1356 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 292 | train 0.4576/1.4756 | val 0.8140/1.0653 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 293 | train 0.4423/1.4024 | val 0.8245/1.0501 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 294 | train 0.4772/1.4288 | val 0.8309/1.0611 | best 0.8351 @ 283

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 295 | train 0.4772/1.5036 | val 0.8457/1.0394 | best 0.8457 @ 295

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 296 | train 0.5069/1.4720 | val 0.8224/1.0607 | best 0.8457 @ 295

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 297 | train 0.4952/1.4807 | val 0.8309/1.0487 | best 0.8457 @ 295

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 298 | train 0.5048/1.3796 | val 0.8309/1.0397 | best 0.8457 @ 295

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 299 | train 0.4650/1.4616 | val 0.8372/1.0642 | best 0.8457 @ 295

  0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold1 | ep 300 | train 0.4518/1.4827 | val 0.8161/1.1051 | best 0.8457 @ 295

SWA BN:   0%|          | 0/59 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

SWA (106 snapshots) val acc: 0.8076  |  best ckpt: 0.8457
-> Keeping best checkpoint

  0%|          | 0/25 [00:00<?, ?it/s]

Saved: /home/onyxia/work/tilda-texture-classification/outputs/submissions/submission_seresnet50_bilinear_v3_patch_fold1_tta_labels0.csv
label
0    142
1     88
2    114
3    100
4     76
5     86
6    100
7     83
Name: count, dtype: int64

================================================================================
seresnet50_bilinear_v3_patch | fold 2/5
================================================================================

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 001 | train 0.1228/2.0802 | val 0.1271/2.0779 | best 0.1271 @ 1

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 002 | train 0.1191/2.0809 | val 0.1271/2.0773 | best 0.1271 @ 1

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 003 | train 0.1281/2.0808 | val 0.1568/2.0750 | best 0.1568 @ 3

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 004 | train 0.1255/2.0804 | val 0.1631/2.0748 | best 0.1631 @ 4

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 005 | train 0.1488/2.0759 | val 0.1928/2.0607 | best 0.1928 @ 5

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 006 | train 0.1509/2.0644 | val 0.1949/2.0385 | best 0.1949 @ 6

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 007 | train 0.1742/2.0516 | val 0.2140/1.9996 | best 0.2140 @ 7

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 008 | train 0.1879/2.0305 | val 0.1907/2.0025 | best 0.2140 @ 7

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 009 | train 0.1540/2.0357 | val 0.2331/1.9688 | best 0.2331 @ 9

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 010 | train 0.1848/2.0205 | val 0.1992/1.9516 | best 0.2331 @ 9

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 011 | train 0.1758/2.0081 | val 0.1992/1.9902 | best 0.2331 @ 9

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 012 | train 0.2028/1.9963 | val 0.2542/1.9389 | best 0.2542 @ 12

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 013 | train 0.2012/2.0091 | val 0.2818/1.9096 | best 0.2818 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 014 | train 0.1959/1.9912 | val 0.2500/1.9350 | best 0.2818 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 015 | train 0.1943/1.9914 | val 0.2309/1.9201 | best 0.2818 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 016 | train 0.2133/1.9711 | val 0.2479/1.8877 | best 0.2818 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 017 | train 0.1990/1.9699 | val 0.3347/1.8488 | best 0.3347 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 018 | train 0.2075/1.9765 | val 0.2733/1.8857 | best 0.3347 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 019 | train 0.2234/1.9519 | val 0.3305/1.8502 | best 0.3347 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 020 | train 0.2303/1.9422 | val 0.3136/1.8260 | best 0.3347 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 021 | train 0.2218/1.9459 | val 0.2500/1.8993 | best 0.3347 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 022 | train 0.2303/1.9262 | val 0.2733/1.8820 | best 0.3347 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 023 | train 0.2382/1.9362 | val 0.3093/1.8161 | best 0.3347 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 024 | train 0.2467/1.9265 | val 0.2860/1.8383 | best 0.3347 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 025 | train 0.2356/1.9341 | val 0.3369/1.8210 | best 0.3369 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 026 | train 0.2462/1.9212 | val 0.3263/1.7922 | best 0.3369 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 027 | train 0.2170/1.9235 | val 0.2712/1.8133 | best 0.3369 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 028 | train 0.2573/1.9156 | val 0.1907/2.0261 | best 0.3369 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 029 | train 0.2208/1.9233 | val 0.3453/1.7817 | best 0.3453 @ 29

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 030 | train 0.2303/1.8921 | val 0.4004/1.7472 | best 0.4004 @ 30

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 031 | train 0.2573/1.8912 | val 0.3369/1.7870 | best 0.4004 @ 30

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 032 | train 0.2504/1.8933 | val 0.2542/1.8991 | best 0.4004 @ 30

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 033 | train 0.2324/1.9291 | val 0.2055/2.0253 | best 0.4004 @ 30

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 034 | train 0.2578/1.9003 | val 0.3919/1.7447 | best 0.4004 @ 30

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 035 | train 0.2721/1.9081 | val 0.3708/1.7344 | best 0.4004 @ 30

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 036 | train 0.2493/1.9009 | val 0.4195/1.7311 | best 0.4195 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 037 | train 0.2589/1.8959 | val 0.3602/1.7559 | best 0.4195 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 038 | train 0.2673/1.9044 | val 0.4280/1.7268 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 039 | train 0.2663/1.9088 | val 0.3729/1.7185 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 040 | train 0.2430/1.8785 | val 0.3771/1.7740 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 041 | train 0.2594/1.8896 | val 0.4131/1.7041 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 042 | train 0.2578/1.8691 | val 0.2267/2.0455 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 043 | train 0.2525/1.8864 | val 0.3750/1.7145 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 044 | train 0.2832/1.8685 | val 0.4047/1.7189 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 045 | train 0.2562/1.8826 | val 0.3496/1.7407 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 046 | train 0.2567/1.9220 | val 0.2479/1.8817 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 047 | train 0.2435/1.9175 | val 0.3390/1.7812 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 048 | train 0.2488/1.9197 | val 0.2797/1.9073 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 049 | train 0.2483/1.8920 | val 0.4131/1.7214 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 050 | train 0.2763/1.8506 | val 0.3326/1.7686 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 051 | train 0.2488/1.8800 | val 0.4280/1.6719 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 052 | train 0.2673/1.8514 | val 0.2394/1.9527 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 053 | train 0.2647/1.8982 | val 0.2542/2.0149 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 054 | train 0.2943/1.8587 | val 0.2797/1.8683 | best 0.4280 @ 38

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 055 | train 0.2965/1.8309 | val 0.4343/1.6764 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 056 | train 0.2657/1.8442 | val 0.3729/1.7132 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 057 | train 0.2546/1.8739 | val 0.4110/1.7067 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 058 | train 0.2589/1.8620 | val 0.2585/1.9488 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 059 | train 0.2541/1.8725 | val 0.4047/1.6971 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 060 | train 0.2800/1.8709 | val 0.3602/1.7286 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 061 | train 0.2800/1.8573 | val 0.3919/1.6871 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 062 | train 0.2790/1.8538 | val 0.4068/1.6703 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 063 | train 0.2663/1.8760 | val 0.3877/1.6847 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 064 | train 0.2684/1.8687 | val 0.3178/1.8214 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 065 | train 0.2832/1.8393 | val 0.3708/1.7054 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 066 | train 0.2785/1.8400 | val 0.3072/1.7643 | best 0.4343 @ 55

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 067 | train 0.2758/1.8688 | val 0.4831/1.6238 | best 0.4831 @ 67

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 068 | train 0.2758/1.8491 | val 0.3919/1.7242 | best 0.4831 @ 67

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 069 | train 0.2747/1.8838 | val 0.4386/1.6588 | best 0.4831 @ 67

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 070 | train 0.2806/1.7988 | val 0.4258/1.6480 | best 0.4831 @ 67

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 071 | train 0.2800/1.8616 | val 0.3814/1.7595 | best 0.4831 @ 67

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 072 | train 0.2806/1.8433 | val 0.4386/1.6583 | best 0.4831 @ 67

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 073 | train 0.2822/1.8587 | val 0.4449/1.6271 | best 0.4831 @ 67

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 074 | train 0.2933/1.8139 | val 0.4258/1.6587 | best 0.4831 @ 67

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 075 | train 0.3155/1.8024 | val 0.4915/1.6328 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 076 | train 0.2912/1.8298 | val 0.2818/1.9459 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 077 | train 0.3219/1.8188 | val 0.4831/1.6219 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 078 | train 0.2806/1.8390 | val 0.3771/1.7711 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 079 | train 0.3007/1.8211 | val 0.4047/1.6437 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 080 | train 0.2636/1.8619 | val 0.4386/1.6758 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 081 | train 0.3240/1.8214 | val 0.3496/1.8200 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 082 | train 0.3192/1.8452 | val 0.4873/1.6318 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 083 | train 0.2832/1.8449 | val 0.1928/2.0819 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 084 | train 0.2726/1.8925 | val 0.2754/1.8496 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 085 | train 0.2790/1.8269 | val 0.3686/1.7541 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 086 | train 0.2843/1.8365 | val 0.4534/1.6245 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 087 | train 0.2906/1.8409 | val 0.4555/1.6610 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 088 | train 0.2615/1.8579 | val 0.4047/1.6969 | best 0.4915 @ 75

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 089 | train 0.2716/1.8216 | val 0.5042/1.6255 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 090 | train 0.2795/1.8138 | val 0.3792/1.6920 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 091 | train 0.3235/1.8231 | val 0.4428/1.6512 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 092 | train 0.2742/1.8248 | val 0.2267/1.9860 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 093 | train 0.3282/1.8176 | val 0.4958/1.6173 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 094 | train 0.3081/1.8067 | val 0.4915/1.6112 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 095 | train 0.2827/1.8064 | val 0.4237/1.6979 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 096 | train 0.3404/1.8005 | val 0.4216/1.6223 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 097 | train 0.3065/1.8083 | val 0.3030/1.8495 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 098 | train 0.2885/1.7979 | val 0.2500/1.9299 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 099 | train 0.3097/1.8080 | val 0.4131/1.6873 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 100 | train 0.3007/1.8098 | val 0.3178/1.8780 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 101 | train 0.3256/1.8042 | val 0.3771/1.7089 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 102 | train 0.3319/1.8089 | val 0.4364/1.6523 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 103 | train 0.3113/1.7617 | val 0.4576/1.6099 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 104 | train 0.3235/1.7586 | val 0.3157/1.8428 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 105 | train 0.3107/1.7834 | val 0.2839/1.9463 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 106 | train 0.3176/1.7533 | val 0.4936/1.5955 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 107 | train 0.2885/1.8107 | val 0.3729/1.8191 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 108 | train 0.3610/1.7466 | val 0.4407/1.6537 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 109 | train 0.3240/1.8383 | val 0.4237/1.6641 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 110 | train 0.3256/1.7733 | val 0.4831/1.5838 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 111 | train 0.3372/1.7692 | val 0.3051/1.9521 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 112 | train 0.3272/1.7394 | val 0.4068/1.7154 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 113 | train 0.3118/1.7905 | val 0.4258/1.6161 | best 0.5042 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 114 | train 0.3526/1.7437 | val 0.5106/1.5377 | best 0.5106 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 115 | train 0.3197/1.7877 | val 0.2839/1.8696 | best 0.5106 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 116 | train 0.3319/1.7838 | val 0.3475/1.7512 | best 0.5106 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 117 | train 0.3187/1.7651 | val 0.5021/1.5910 | best 0.5106 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 118 | train 0.3404/1.7764 | val 0.4174/1.7190 | best 0.5106 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 119 | train 0.3383/1.7490 | val 0.3242/1.8328 | best 0.5106 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 120 | train 0.3372/1.7665 | val 0.4343/1.7059 | best 0.5106 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 121 | train 0.3547/1.7816 | val 0.5339/1.5222 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 122 | train 0.3584/1.7516 | val 0.4936/1.5454 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 123 | train 0.3192/1.7736 | val 0.4131/1.6651 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 124 | train 0.3272/1.8061 | val 0.4195/1.6481 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 125 | train 0.3684/1.7583 | val 0.4852/1.5992 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 126 | train 0.3049/1.7664 | val 0.4831/1.6381 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 127 | train 0.3473/1.7329 | val 0.4131/1.6404 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 128 | train 0.3467/1.7753 | val 0.5106/1.5136 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 129 | train 0.3330/1.7034 | val 0.4153/1.6805 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 130 | train 0.3250/1.7820 | val 0.4852/1.5837 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 131 | train 0.3166/1.7667 | val 0.4216/1.6567 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 132 | train 0.3526/1.7379 | val 0.4237/1.6475 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 133 | train 0.2954/1.7818 | val 0.4746/1.5803 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 134 | train 0.3372/1.7530 | val 0.4725/1.5475 | best 0.5339 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 135 | train 0.3160/1.7743 | val 0.5699/1.4732 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 136 | train 0.3367/1.7691 | val 0.4555/1.5845 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 137 | train 0.3917/1.7123 | val 0.4449/1.6589 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 138 | train 0.3875/1.7352 | val 0.4131/1.6552 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 139 | train 0.3377/1.7572 | val 0.3941/1.6940 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 140 | train 0.3441/1.7242 | val 0.4682/1.6433 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 141 | train 0.3097/1.7313 | val 0.5021/1.5723 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 142 | train 0.3335/1.7350 | val 0.3856/1.7286 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 143 | train 0.3764/1.7453 | val 0.4936/1.5370 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 144 | train 0.3494/1.7146 | val 0.5636/1.4537 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 145 | train 0.3319/1.7580 | val 0.4619/1.5806 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 146 | train 0.3515/1.7664 | val 0.4852/1.5459 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 147 | train 0.3250/1.7414 | val 0.4555/1.6722 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 148 | train 0.3049/1.7829 | val 0.5339/1.5443 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 149 | train 0.3452/1.7530 | val 0.5318/1.5309 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 150 | train 0.3632/1.7702 | val 0.3475/1.7981 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 151 | train 0.3849/1.7440 | val 0.5530/1.5215 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 152 | train 0.3626/1.7193 | val 0.4958/1.5480 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 153 | train 0.3753/1.7217 | val 0.5275/1.4867 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 154 | train 0.3790/1.7205 | val 0.3305/1.9191 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 155 | train 0.3055/1.7465 | val 0.5233/1.5038 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 156 | train 0.3933/1.6937 | val 0.4958/1.5556 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 157 | train 0.3706/1.7134 | val 0.4470/1.6548 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 158 | train 0.3854/1.6891 | val 0.5254/1.5376 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 159 | train 0.3626/1.7262 | val 0.5021/1.5420 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 160 | train 0.3499/1.6924 | val 0.4831/1.5640 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 161 | train 0.3420/1.7599 | val 0.5212/1.5485 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 162 | train 0.3017/1.7818 | val 0.3538/1.7430 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 163 | train 0.3679/1.6990 | val 0.4110/1.6888 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 164 | train 0.3727/1.7024 | val 0.5064/1.5082 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 165 | train 0.3647/1.6848 | val 0.4682/1.6105 | best 0.5699 @ 135

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 166 | train 0.3584/1.7026 | val 0.5826/1.4186 | best 0.5826 @ 166

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 167 | train 0.3393/1.7091 | val 0.5254/1.5306 | best 0.5826 @ 166

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 168 | train 0.3023/1.7322 | val 0.4894/1.6202 | best 0.5826 @ 166

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 169 | train 0.3653/1.6632 | val 0.6186/1.3890 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 170 | train 0.3669/1.6711 | val 0.5614/1.4024 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 171 | train 0.3653/1.6861 | val 0.4089/1.6984 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 172 | train 0.3081/1.7389 | val 0.5466/1.4433 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 173 | train 0.3610/1.7076 | val 0.5572/1.4490 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 174 | train 0.3309/1.7368 | val 0.4555/1.5893 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 175 | train 0.4119/1.6741 | val 0.5042/1.5368 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 176 | train 0.3774/1.6758 | val 0.5847/1.3948 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 177 | train 0.4066/1.6421 | val 0.5275/1.5327 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 178 | train 0.3817/1.7014 | val 0.5275/1.4644 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 179 | train 0.3552/1.7567 | val 0.4343/1.6908 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 180 | train 0.3976/1.6906 | val 0.5720/1.4198 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 181 | train 0.3838/1.6825 | val 0.4280/1.6388 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 182 | train 0.3409/1.6898 | val 0.5318/1.5066 | best 0.6186 @ 169

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 183 | train 0.3780/1.6257 | val 0.6419/1.3538 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 184 | train 0.3298/1.7133 | val 0.4428/1.5752 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 185 | train 0.3843/1.6841 | val 0.4301/1.6510 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 186 | train 0.3473/1.6746 | val 0.6038/1.4109 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 187 | train 0.3827/1.6511 | val 0.4492/1.6366 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 188 | train 0.3753/1.7053 | val 0.4852/1.5727 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 189 | train 0.3748/1.7072 | val 0.4958/1.5223 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 190 | train 0.3340/1.6935 | val 0.5805/1.4175 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 191 | train 0.3944/1.6593 | val 0.5678/1.4404 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 192 | train 0.3764/1.6794 | val 0.3750/1.7169 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 193 | train 0.3833/1.7031 | val 0.5869/1.4245 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 194 | train 0.3960/1.6784 | val 0.4809/1.5045 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 195 | train 0.4113/1.6613 | val 0.5297/1.4893 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 196 | train 0.3642/1.6926 | val 0.4746/1.6014 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 197 | train 0.4113/1.6595 | val 0.6123/1.4030 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 198 | train 0.3748/1.6799 | val 0.5636/1.4255 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 199 | train 0.3547/1.6219 | val 0.6271/1.3360 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 200 | train 0.4442/1.5832 | val 0.6059/1.3559 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 201 | train 0.4124/1.6612 | val 0.5932/1.3883 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 202 | train 0.3600/1.7237 | val 0.5784/1.4404 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 203 | train 0.3849/1.6821 | val 0.5148/1.5019 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 204 | train 0.3573/1.6540 | val 0.5975/1.3794 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 205 | train 0.3976/1.6242 | val 0.5191/1.5126 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 206 | train 0.3759/1.6317 | val 0.3072/2.0171 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 207 | train 0.3949/1.6698 | val 0.5847/1.3617 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 208 | train 0.3923/1.6579 | val 0.4725/1.5709 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 209 | train 0.4082/1.6522 | val 0.5381/1.4688 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 210 | train 0.4203/1.6577 | val 0.4322/1.6349 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 211 | train 0.3695/1.6915 | val 0.5932/1.3613 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 212 | train 0.3716/1.6595 | val 0.5212/1.4960 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 213 | train 0.3970/1.6443 | val 0.4873/1.5412 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 214 | train 0.3722/1.6387 | val 0.4343/1.6174 | best 0.6419 @ 183

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 215 | train 0.3997/1.7053 | val 0.6441/1.3509 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 216 | train 0.4071/1.6593 | val 0.5212/1.4651 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 217 | train 0.4129/1.6253 | val 0.5742/1.3993 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 218 | train 0.4251/1.6572 | val 0.5042/1.5117 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 219 | train 0.3917/1.6502 | val 0.6292/1.3430 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 220 | train 0.4039/1.6454 | val 0.6102/1.3479 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 221 | train 0.4627/1.5874 | val 0.4894/1.5518 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 222 | train 0.3864/1.5487 | val 0.5297/1.4564 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 223 | train 0.4039/1.6220 | val 0.6229/1.3470 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 224 | train 0.3960/1.6428 | val 0.4831/1.5635 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 225 | train 0.3997/1.6288 | val 0.5381/1.5062 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 226 | train 0.3944/1.6108 | val 0.5742/1.4078 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 227 | train 0.4553/1.6103 | val 0.5720/1.4150 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 228 | train 0.3383/1.6025 | val 0.6081/1.3428 | best 0.6441 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 229 | train 0.3552/1.6418 | val 0.6568/1.3272 | best 0.6568 @ 229

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 230 | train 0.3610/1.6247 | val 0.6547/1.3004 | best 0.6568 @ 229

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 231 | train 0.3986/1.6073 | val 0.5847/1.4000 | best 0.6568 @ 229

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 232 | train 0.4156/1.6371 | val 0.6928/1.2948 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 233 | train 0.4007/1.6659 | val 0.4153/1.6382 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 234 | train 0.4108/1.6150 | val 0.5487/1.4503 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 235 | train 0.4129/1.5955 | val 0.4831/1.5717 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 236 | train 0.4473/1.5790 | val 0.5911/1.3899 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 237 | train 0.4336/1.5432 | val 0.6250/1.3214 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 238 | train 0.4039/1.5592 | val 0.4386/1.5930 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 239 | train 0.3827/1.6009 | val 0.6038/1.3381 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 240 | train 0.3838/1.5773 | val 0.6907/1.2282 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 241 | train 0.4452/1.6087 | val 0.6059/1.3436 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 242 | train 0.4103/1.5233 | val 0.6737/1.2408 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 243 | train 0.4060/1.5853 | val 0.6271/1.3406 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 244 | train 0.3817/1.5501 | val 0.6653/1.2541 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 245 | train 0.4479/1.5391 | val 0.4407/1.5541 | best 0.6928 @ 232

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 246 | train 0.4733/1.5860 | val 0.7097/1.2110 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 247 | train 0.4357/1.5424 | val 0.4555/1.5553 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 248 | train 0.3933/1.6187 | val 0.6144/1.3481 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 249 | train 0.4336/1.5643 | val 0.6038/1.3357 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 250 | train 0.4193/1.5744 | val 0.6843/1.2169 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 251 | train 0.3997/1.6044 | val 0.6801/1.2175 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 252 | train 0.4341/1.5711 | val 0.6737/1.2313 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 253 | train 0.4442/1.5620 | val 0.6377/1.3175 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 254 | train 0.4807/1.5713 | val 0.6038/1.3341 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 255 | train 0.4283/1.5650 | val 0.4386/1.6020 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 256 | train 0.4378/1.5611 | val 0.6186/1.3240 | best 0.7097 @ 246

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 257 | train 0.4044/1.5582 | val 0.7119/1.1908 | best 0.7119 @ 257

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 258 | train 0.4240/1.6045 | val 0.6165/1.2791 | best 0.7119 @ 257

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 259 | train 0.4119/1.5539 | val 0.6144/1.3307 | best 0.7119 @ 257

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 260 | train 0.4537/1.5358 | val 0.6674/1.2602 | best 0.7119 @ 257

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 261 | train 0.3965/1.5474 | val 0.6271/1.3122 | best 0.7119 @ 257

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 262 | train 0.4187/1.5146 | val 0.4936/1.5196 | best 0.7119 @ 257

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 263 | train 0.4600/1.5009 | val 0.6801/1.2159 | best 0.7119 @ 257

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 264 | train 0.4124/1.5675 | val 0.7161/1.2013 | best 0.7161 @ 264

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 265 | train 0.4256/1.5880 | val 0.6843/1.1966 | best 0.7161 @ 264

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 266 | train 0.4404/1.5343 | val 0.6186/1.2909 | best 0.7161 @ 264

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 267 | train 0.3896/1.5648 | val 0.7140/1.2068 | best 0.7161 @ 264

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 268 | train 0.4415/1.5787 | val 0.7585/1.1609 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 269 | train 0.4023/1.5554 | val 0.5784/1.3563 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 270 | train 0.4531/1.5833 | val 0.7203/1.1996 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 271 | train 0.4325/1.5200 | val 0.4619/1.5633 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 272 | train 0.5008/1.4616 | val 0.6695/1.2658 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 273 | train 0.4653/1.5467 | val 0.6653/1.2844 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 274 | train 0.4616/1.5305 | val 0.6886/1.2110 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 275 | train 0.4547/1.5201 | val 0.6419/1.2764 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 276 | train 0.4754/1.5238 | val 0.5826/1.3514 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 277 | train 0.4807/1.5726 | val 0.5805/1.3749 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 278 | train 0.4103/1.5734 | val 0.7309/1.1733 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 279 | train 0.4066/1.5311 | val 0.5593/1.3841 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 280 | train 0.4812/1.4947 | val 0.6504/1.2880 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 281 | train 0.4680/1.4938 | val 0.6716/1.2164 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 282 | train 0.4468/1.5285 | val 0.5530/1.4132 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 283 | train 0.4283/1.5104 | val 0.7309/1.1739 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 284 | train 0.4923/1.4800 | val 0.6144/1.3217 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 285 | train 0.4203/1.5477 | val 0.5254/1.4666 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 286 | train 0.4320/1.5386 | val 0.6780/1.2055 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 287 | train 0.4113/1.4726 | val 0.6695/1.2250 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 288 | train 0.4547/1.4790 | val 0.6208/1.3002 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 289 | train 0.4637/1.5146 | val 0.6419/1.2842 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 290 | train 0.4987/1.5218 | val 0.7479/1.1554 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 291 | train 0.4542/1.5318 | val 0.7246/1.1414 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 292 | train 0.4733/1.5499 | val 0.6758/1.2739 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 293 | train 0.4690/1.5809 | val 0.6864/1.2190 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 294 | train 0.4770/1.4985 | val 0.7436/1.1639 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 295 | train 0.4203/1.5239 | val 0.6780/1.2109 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 296 | train 0.4224/1.5729 | val 0.6928/1.2531 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 297 | train 0.4336/1.5569 | val 0.6864/1.2383 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 298 | train 0.4558/1.5300 | val 0.7097/1.1905 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 299 | train 0.4733/1.4687 | val 0.6314/1.3094 | best 0.7585 @ 268

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold2 | ep 300 | train 0.4717/1.4757 | val 0.7331/1.2039 | best 0.7585 @ 268

SWA BN:   0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

SWA (106 snapshots) val acc: 0.7309  |  best ckpt: 0.7585
-> Keeping best checkpoint

  0%|          | 0/25 [00:00<?, ?it/s]

Saved: /home/onyxia/work/tilda-texture-classification/outputs/submissions/submission_seresnet50_bilinear_v3_patch_fold2_tta_labels0.csv
label
0    138
1     80
2     93
3    117
4     64
5     78
6    114
7    105
Name: count, dtype: int64

================================================================================
seresnet50_bilinear_v3_patch | fold 3/5
================================================================================

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 001 | train 0.1143/2.0802 | val 0.1610/2.0782 | best 0.1610 @ 1

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 002 | train 0.1239/2.0801 | val 0.1271/2.0783 | best 0.1610 @ 1

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 003 | train 0.1175/2.0827 | val 0.1568/2.0761 | best 0.1610 @ 1

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 004 | train 0.1286/2.0800 | val 0.1271/2.0717 | best 0.1610 @ 1

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 005 | train 0.1260/2.0786 | val 0.1970/2.0590 | best 0.1970 @ 5

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 006 | train 0.1578/2.0691 | val 0.1716/2.0344 | best 0.1970 @ 5

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 007 | train 0.1546/2.0507 | val 0.2013/2.0223 | best 0.2013 @ 7

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 008 | train 0.1556/2.0344 | val 0.2140/1.9707 | best 0.2140 @ 8

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 009 | train 0.1742/2.0301 | val 0.2394/1.9869 | best 0.2394 @ 9

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 010 | train 0.1885/2.0187 | val 0.2352/1.9430 | best 0.2394 @ 9

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 011 | train 0.1848/2.0104 | val 0.2161/1.9354 | best 0.2394 @ 9

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 012 | train 0.1890/2.0014 | val 0.2585/1.9083 | best 0.2585 @ 12

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 013 | train 0.2043/1.9939 | val 0.2839/1.8880 | best 0.2839 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 014 | train 0.2139/1.9879 | val 0.2055/1.9756 | best 0.2839 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 015 | train 0.2001/1.9761 | val 0.2733/1.8833 | best 0.2839 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 016 | train 0.1975/1.9824 | val 0.2754/1.9186 | best 0.2839 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 017 | train 0.2165/1.9619 | val 0.2394/1.9355 | best 0.2839 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 018 | train 0.2292/1.9558 | val 0.2352/1.9288 | best 0.2839 @ 13

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 019 | train 0.2229/1.9396 | val 0.3114/1.8400 | best 0.3114 @ 19

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 020 | train 0.2218/1.9716 | val 0.2797/1.8758 | best 0.3114 @ 19

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 021 | train 0.2287/1.9388 | val 0.3369/1.7962 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 022 | train 0.2382/1.9393 | val 0.2627/1.8834 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 023 | train 0.2467/1.9339 | val 0.2225/1.8689 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 024 | train 0.2594/1.9195 | val 0.2585/1.9086 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 025 | train 0.2388/1.9373 | val 0.2246/1.9114 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 026 | train 0.2319/1.9240 | val 0.2924/1.7880 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 027 | train 0.2398/1.9189 | val 0.2394/1.9206 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 028 | train 0.2324/1.9004 | val 0.3369/1.8177 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 029 | train 0.2663/1.9044 | val 0.2881/1.7977 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 030 | train 0.2504/1.9171 | val 0.3093/1.7974 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 031 | train 0.2435/1.8862 | val 0.3369/1.7945 | best 0.3369 @ 21

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 032 | train 0.2345/1.9111 | val 0.3475/1.7977 | best 0.3475 @ 32

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 033 | train 0.2234/1.9063 | val 0.2987/1.8306 | best 0.3475 @ 32

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 034 | train 0.2615/1.9090 | val 0.3390/1.7620 | best 0.3475 @ 32

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 035 | train 0.2663/1.8990 | val 0.2606/1.8645 | best 0.3475 @ 32

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 036 | train 0.2615/1.8847 | val 0.3729/1.7288 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 037 | train 0.2419/1.9045 | val 0.3030/1.8339 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 038 | train 0.2414/1.9185 | val 0.2797/1.8309 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 039 | train 0.2409/1.9015 | val 0.2606/1.8909 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 040 | train 0.2657/1.8772 | val 0.3496/1.7654 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 041 | train 0.2557/1.9039 | val 0.3347/1.7665 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 042 | train 0.2493/1.9159 | val 0.3326/1.7619 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 043 | train 0.2599/1.8929 | val 0.3432/1.7387 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 044 | train 0.2562/1.8853 | val 0.2818/1.8755 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 045 | train 0.2779/1.8692 | val 0.2521/1.9081 | best 0.3729 @ 36

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 046 | train 0.2435/1.8987 | val 0.4364/1.6840 | best 0.4364 @ 46

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 047 | train 0.2467/1.8948 | val 0.4555/1.7008 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 048 | train 0.2483/1.9075 | val 0.3941/1.7472 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 049 | train 0.2541/1.8823 | val 0.3623/1.7809 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 050 | train 0.2843/1.8691 | val 0.3030/1.8804 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 051 | train 0.2880/1.8944 | val 0.4004/1.7451 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 052 | train 0.2716/1.8892 | val 0.3157/1.8056 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 053 | train 0.2509/1.9063 | val 0.3856/1.8072 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 054 | train 0.2716/1.9003 | val 0.2860/1.8183 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 055 | train 0.2562/1.8851 | val 0.3347/1.7532 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 056 | train 0.2642/1.8791 | val 0.3919/1.7110 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 057 | train 0.2620/1.8941 | val 0.3729/1.7449 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 058 | train 0.2615/1.8732 | val 0.3856/1.7786 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 059 | train 0.2472/1.8447 | val 0.3898/1.7059 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 060 | train 0.2642/1.8501 | val 0.4004/1.6982 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 061 | train 0.2827/1.8495 | val 0.3750/1.7172 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 062 | train 0.2631/1.8666 | val 0.3877/1.7047 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 063 | train 0.2980/1.8723 | val 0.2606/1.9568 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 064 | train 0.2816/1.8592 | val 0.3242/1.8547 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 065 | train 0.2943/1.8371 | val 0.2987/1.7902 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 066 | train 0.2901/1.8543 | val 0.3898/1.7477 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 067 | train 0.2785/1.8803 | val 0.3686/1.7271 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 068 | train 0.3039/1.8440 | val 0.4153/1.6922 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 069 | train 0.2605/1.8614 | val 0.2669/1.8063 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 070 | train 0.2530/1.8623 | val 0.3602/1.7400 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 071 | train 0.2652/1.8832 | val 0.2712/1.9207 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 072 | train 0.2626/1.8330 | val 0.3962/1.7044 | best 0.4555 @ 47

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 073 | train 0.2790/1.8438 | val 0.4788/1.6448 | best 0.4788 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 074 | train 0.3070/1.8301 | val 0.3347/1.8550 | best 0.4788 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 075 | train 0.2806/1.8514 | val 0.4301/1.6651 | best 0.4788 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 076 | train 0.2620/1.8144 | val 0.3941/1.6773 | best 0.4788 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 077 | train 0.3055/1.8375 | val 0.3623/1.7027 | best 0.4788 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 078 | train 0.2912/1.8156 | val 0.3792/1.7227 | best 0.4788 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 079 | train 0.2753/1.8641 | val 0.3347/1.7891 | best 0.4788 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 080 | train 0.2763/1.8359 | val 0.5000/1.6010 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 081 | train 0.2901/1.8471 | val 0.3962/1.7056 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 082 | train 0.3060/1.8493 | val 0.3178/1.8361 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 083 | train 0.2779/1.8376 | val 0.4703/1.6240 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 084 | train 0.2509/1.8349 | val 0.4047/1.6738 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 085 | train 0.3028/1.8111 | val 0.4492/1.6308 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 086 | train 0.2668/1.8660 | val 0.3305/1.7823 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 087 | train 0.2896/1.8114 | val 0.3898/1.7003 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 088 | train 0.2864/1.8213 | val 0.3178/1.8514 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 089 | train 0.2906/1.8608 | val 0.4534/1.6300 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 090 | train 0.3065/1.8479 | val 0.4513/1.6339 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 091 | train 0.2965/1.7859 | val 0.3686/1.7088 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 092 | train 0.2965/1.8457 | val 0.3835/1.7270 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 093 | train 0.3129/1.8299 | val 0.4004/1.7061 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 094 | train 0.2578/1.8130 | val 0.4703/1.6278 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 095 | train 0.2848/1.8111 | val 0.4386/1.6288 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 096 | train 0.2917/1.8232 | val 0.3114/1.7967 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 097 | train 0.3129/1.8252 | val 0.4110/1.6943 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 098 | train 0.3002/1.8258 | val 0.4873/1.6160 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 099 | train 0.3060/1.8423 | val 0.3941/1.6540 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 100 | train 0.2853/1.8228 | val 0.4110/1.7149 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 101 | train 0.2896/1.7972 | val 0.3475/1.7920 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 102 | train 0.3208/1.8018 | val 0.4407/1.6416 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 103 | train 0.3028/1.8577 | val 0.4534/1.6324 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 104 | train 0.3145/1.8284 | val 0.4174/1.6978 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 105 | train 0.2848/1.8248 | val 0.4597/1.6292 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 106 | train 0.2933/1.8151 | val 0.3686/1.7074 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 107 | train 0.2991/1.7831 | val 0.3517/1.7705 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 108 | train 0.3182/1.8130 | val 0.4470/1.6529 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 109 | train 0.3293/1.8192 | val 0.4280/1.6659 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 110 | train 0.2811/1.8009 | val 0.4047/1.7320 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 111 | train 0.3113/1.7896 | val 0.4153/1.7026 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 112 | train 0.3049/1.8055 | val 0.4661/1.5775 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 113 | train 0.2774/1.7759 | val 0.4915/1.5609 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 114 | train 0.3145/1.8478 | val 0.3877/1.7523 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 115 | train 0.2668/1.8083 | val 0.4343/1.7017 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 116 | train 0.2965/1.7898 | val 0.4873/1.5495 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 117 | train 0.3166/1.8170 | val 0.4089/1.6650 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 118 | train 0.3049/1.7837 | val 0.4004/1.6565 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 119 | train 0.3092/1.8313 | val 0.3962/1.6966 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 120 | train 0.3235/1.7845 | val 0.3263/1.7921 | best 0.5000 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 121 | train 0.3118/1.7809 | val 0.5445/1.5258 | best 0.5445 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 122 | train 0.3092/1.7525 | val 0.4979/1.5672 | best 0.5445 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 123 | train 0.3192/1.7933 | val 0.4386/1.6515 | best 0.5445 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 124 | train 0.3129/1.7817 | val 0.4131/1.6593 | best 0.5445 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 125 | train 0.3430/1.7788 | val 0.4047/1.6952 | best 0.5445 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 126 | train 0.3346/1.7756 | val 0.4661/1.5781 | best 0.5445 @ 121

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 127 | train 0.3335/1.7942 | val 0.5466/1.5220 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 128 | train 0.3092/1.7907 | val 0.5254/1.5566 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 129 | train 0.3579/1.7479 | val 0.4746/1.5879 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 130 | train 0.2933/1.7903 | val 0.4407/1.6194 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 131 | train 0.3044/1.7867 | val 0.4979/1.5581 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 132 | train 0.3499/1.7948 | val 0.5064/1.5862 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 133 | train 0.3171/1.7995 | val 0.5064/1.5877 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 134 | train 0.3325/1.7824 | val 0.5064/1.5379 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 135 | train 0.3197/1.7479 | val 0.4513/1.6060 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 136 | train 0.3372/1.7513 | val 0.4746/1.5614 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 137 | train 0.3409/1.7403 | val 0.4110/1.6564 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 138 | train 0.3764/1.7404 | val 0.3835/1.7637 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 139 | train 0.3277/1.7506 | val 0.4703/1.5783 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 140 | train 0.3452/1.7732 | val 0.4915/1.5884 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 141 | train 0.3346/1.7966 | val 0.4068/1.6756 | best 0.5466 @ 127

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 142 | train 0.3600/1.7298 | val 0.5720/1.4646 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 143 | train 0.3489/1.7389 | val 0.5021/1.5601 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 144 | train 0.3134/1.8079 | val 0.4725/1.6059 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 145 | train 0.3526/1.7472 | val 0.4576/1.6145 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 146 | train 0.3293/1.7526 | val 0.5085/1.6099 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 147 | train 0.3647/1.7051 | val 0.4449/1.6056 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 148 | train 0.3420/1.7278 | val 0.4661/1.5965 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 149 | train 0.3679/1.7445 | val 0.4725/1.5431 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 150 | train 0.3356/1.7300 | val 0.3856/1.6738 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 151 | train 0.3589/1.7445 | val 0.5360/1.5138 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 152 | train 0.3362/1.7449 | val 0.4746/1.5636 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 153 | train 0.3621/1.7331 | val 0.4746/1.5942 | best 0.5720 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 154 | train 0.3139/1.7005 | val 0.5826/1.4465 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 155 | train 0.3383/1.7199 | val 0.5572/1.4780 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 156 | train 0.3632/1.7298 | val 0.5487/1.4916 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 157 | train 0.3436/1.7777 | val 0.4343/1.6176 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 158 | train 0.3256/1.7324 | val 0.5064/1.5747 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 159 | train 0.3520/1.7272 | val 0.5148/1.5245 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 160 | train 0.3700/1.7317 | val 0.4534/1.6216 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 161 | train 0.3330/1.7471 | val 0.5763/1.4781 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 162 | train 0.3684/1.7300 | val 0.1992/2.2793 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 163 | train 0.3023/1.7499 | val 0.4809/1.5736 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 164 | train 0.3875/1.7051 | val 0.4746/1.5952 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 165 | train 0.3197/1.6630 | val 0.4915/1.5732 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 166 | train 0.3997/1.7194 | val 0.5466/1.5326 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 167 | train 0.3880/1.7187 | val 0.4831/1.5156 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 168 | train 0.3700/1.7356 | val 0.5593/1.4770 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 169 | train 0.3113/1.6494 | val 0.5000/1.4908 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 170 | train 0.3547/1.7163 | val 0.2966/1.9630 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 171 | train 0.3589/1.6754 | val 0.4364/1.6276 | best 0.5826 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 172 | train 0.3388/1.6867 | val 0.6144/1.4109 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 173 | train 0.3473/1.7119 | val 0.5106/1.5037 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 174 | train 0.3457/1.7199 | val 0.6017/1.4144 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 175 | train 0.3716/1.7289 | val 0.4047/1.6690 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 176 | train 0.3663/1.6867 | val 0.4280/1.6282 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 177 | train 0.4044/1.7039 | val 0.5360/1.4832 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 178 | train 0.3579/1.7259 | val 0.5212/1.5152 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 179 | train 0.3669/1.6625 | val 0.5911/1.4650 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 180 | train 0.3976/1.6664 | val 0.5636/1.4335 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 181 | train 0.3425/1.6938 | val 0.5847/1.4442 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 182 | train 0.4103/1.6567 | val 0.4470/1.5572 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 183 | train 0.3245/1.7275 | val 0.5487/1.4970 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 184 | train 0.3843/1.6801 | val 0.5847/1.4657 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 185 | train 0.3430/1.6637 | val 0.4428/1.6135 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 186 | train 0.3203/1.6886 | val 0.5127/1.5146 | best 0.6144 @ 172

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 187 | train 0.3589/1.6970 | val 0.6610/1.3586 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 188 | train 0.3939/1.6548 | val 0.4449/1.6579 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 189 | train 0.3399/1.6952 | val 0.5996/1.4055 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 190 | train 0.3886/1.7010 | val 0.5763/1.4530 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 191 | train 0.3790/1.7127 | val 0.6102/1.3996 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 192 | train 0.4039/1.6404 | val 0.5636/1.4406 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 193 | train 0.3965/1.6549 | val 0.4788/1.5463 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 194 | train 0.3732/1.6225 | val 0.6165/1.3711 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 195 | train 0.3886/1.7343 | val 0.6123/1.4004 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 196 | train 0.3711/1.6550 | val 0.6038/1.3688 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 197 | train 0.3642/1.6783 | val 0.3538/1.7932 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 198 | train 0.3759/1.6390 | val 0.5530/1.4410 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 199 | train 0.3912/1.6360 | val 0.5678/1.4182 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 200 | train 0.3356/1.6627 | val 0.5233/1.5659 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 201 | train 0.3700/1.6824 | val 0.5826/1.4037 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 202 | train 0.4113/1.6869 | val 0.6398/1.3291 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 203 | train 0.4129/1.6282 | val 0.5297/1.4944 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 204 | train 0.3653/1.6809 | val 0.5106/1.4571 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 205 | train 0.4383/1.6316 | val 0.6229/1.3776 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 206 | train 0.4060/1.6583 | val 0.6208/1.3657 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 207 | train 0.3626/1.6846 | val 0.5572/1.4845 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 208 | train 0.4029/1.6603 | val 0.5530/1.4847 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 209 | train 0.3880/1.7074 | val 0.5699/1.4670 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 210 | train 0.4521/1.6086 | val 0.6441/1.3229 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 211 | train 0.4066/1.6269 | val 0.5508/1.4706 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 212 | train 0.3706/1.6377 | val 0.5636/1.4191 | best 0.6610 @ 187

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 213 | train 0.4050/1.6079 | val 0.6695/1.3238 | best 0.6695 @ 213

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 214 | train 0.4267/1.6424 | val 0.5445/1.4617 | best 0.6695 @ 213

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 215 | train 0.3827/1.6142 | val 0.5742/1.3917 | best 0.6695 @ 213

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 216 | train 0.3917/1.6792 | val 0.6653/1.3450 | best 0.6695 @ 213

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 217 | train 0.3992/1.6424 | val 0.4788/1.5614 | best 0.6695 @ 213

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 218 | train 0.3425/1.6553 | val 0.4873/1.5392 | best 0.6695 @ 213

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 219 | train 0.3954/1.6505 | val 0.5127/1.4968 | best 0.6695 @ 213

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 220 | train 0.3827/1.6472 | val 0.6631/1.3437 | best 0.6695 @ 213

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 221 | train 0.3854/1.6377 | val 0.7034/1.2686 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 222 | train 0.4193/1.5384 | val 0.6335/1.3506 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 223 | train 0.4150/1.5958 | val 0.6568/1.3300 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 224 | train 0.4383/1.6577 | val 0.6271/1.3461 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 225 | train 0.4214/1.6310 | val 0.5424/1.4066 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 226 | train 0.4029/1.6523 | val 0.6525/1.3486 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 227 | train 0.3875/1.6321 | val 0.5953/1.3764 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 228 | train 0.4526/1.5849 | val 0.5466/1.4183 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 229 | train 0.4442/1.5697 | val 0.4831/1.5393 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 230 | train 0.3923/1.6608 | val 0.4725/1.5610 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 231 | train 0.4309/1.6038 | val 0.6123/1.3680 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 232 | train 0.4288/1.5709 | val 0.6165/1.3635 | best 0.7034 @ 221

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 233 | train 0.4002/1.6178 | val 0.7119/1.2544 | best 0.7119 @ 233

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 234 | train 0.3769/1.5906 | val 0.6419/1.3508 | best 0.7119 @ 233

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 235 | train 0.4457/1.5974 | val 0.6483/1.3199 | best 0.7119 @ 233

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 236 | train 0.4097/1.5501 | val 0.6886/1.2788 | best 0.7119 @ 233

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 237 | train 0.4198/1.6143 | val 0.6737/1.2847 | best 0.7119 @ 233

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 238 | train 0.3949/1.6339 | val 0.6335/1.3187 | best 0.7119 @ 233

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 239 | train 0.3870/1.6063 | val 0.7564/1.2423 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 240 | train 0.4209/1.6230 | val 0.6992/1.2660 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 241 | train 0.4648/1.5752 | val 0.5487/1.4100 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 242 | train 0.4373/1.5956 | val 0.6144/1.3466 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 243 | train 0.4013/1.5913 | val 0.6419/1.3012 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 244 | train 0.4193/1.5657 | val 0.7013/1.2755 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 245 | train 0.4531/1.6110 | val 0.6208/1.3885 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 246 | train 0.3690/1.5942 | val 0.4894/1.5617 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 247 | train 0.4119/1.6115 | val 0.6186/1.3941 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 248 | train 0.3992/1.5475 | val 0.6038/1.3644 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 249 | train 0.4320/1.5175 | val 0.6589/1.2986 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 250 | train 0.3949/1.5580 | val 0.4470/1.6020 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 251 | train 0.3917/1.5796 | val 0.5996/1.3792 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 252 | train 0.3896/1.6245 | val 0.6165/1.3381 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 253 | train 0.4547/1.5106 | val 0.6801/1.3042 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 254 | train 0.4373/1.5698 | val 0.5678/1.4156 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 255 | train 0.4288/1.5832 | val 0.7500/1.2145 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 256 | train 0.4140/1.6051 | val 0.7182/1.2440 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 257 | train 0.4484/1.5498 | val 0.6653/1.2707 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 258 | train 0.4055/1.5531 | val 0.7458/1.1921 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 259 | train 0.3875/1.5645 | val 0.6864/1.2460 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 260 | train 0.4341/1.5972 | val 0.7500/1.2045 | best 0.7564 @ 239

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 261 | train 0.4436/1.5851 | val 0.7712/1.1726 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 262 | train 0.4711/1.5189 | val 0.7288/1.2304 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 263 | train 0.4733/1.5573 | val 0.6547/1.2781 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 264 | train 0.4521/1.5098 | val 0.6483/1.3361 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 265 | train 0.4463/1.5615 | val 0.5614/1.4254 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 266 | train 0.4727/1.5586 | val 0.7415/1.1652 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 267 | train 0.4442/1.5676 | val 0.5445/1.4490 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 268 | train 0.4219/1.5018 | val 0.7119/1.2330 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 269 | train 0.4738/1.5350 | val 0.7479/1.1732 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 270 | train 0.4420/1.5631 | val 0.7119/1.2506 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 271 | train 0.4547/1.5377 | val 0.7203/1.2339 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 272 | train 0.4187/1.5784 | val 0.5996/1.3776 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 273 | train 0.4680/1.5317 | val 0.6653/1.2987 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 274 | train 0.4404/1.5012 | val 0.7479/1.1636 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 275 | train 0.4452/1.5255 | val 0.7585/1.1854 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 276 | train 0.4394/1.5825 | val 0.6695/1.2928 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 277 | train 0.4277/1.5192 | val 0.6992/1.2588 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 278 | train 0.3870/1.5203 | val 0.7013/1.2532 | best 0.7712 @ 261

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 279 | train 0.4780/1.5422 | val 0.7754/1.1514 | best 0.7754 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 280 | train 0.4701/1.5270 | val 0.7648/1.1900 | best 0.7754 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 281 | train 0.3992/1.5192 | val 0.6992/1.2112 | best 0.7754 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 282 | train 0.4373/1.5646 | val 0.7267/1.2185 | best 0.7754 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 283 | train 0.4325/1.5564 | val 0.7564/1.1677 | best 0.7754 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 284 | train 0.4272/1.5223 | val 0.5763/1.4068 | best 0.7754 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 285 | train 0.4129/1.4897 | val 0.5212/1.4650 | best 0.7754 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 286 | train 0.4817/1.4930 | val 0.7966/1.1258 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 287 | train 0.4918/1.4951 | val 0.7394/1.1915 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 288 | train 0.5034/1.5375 | val 0.7373/1.2234 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 289 | train 0.4404/1.5323 | val 0.7775/1.1522 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 290 | train 0.4436/1.4876 | val 0.6547/1.3075 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 291 | train 0.4050/1.5418 | val 0.6462/1.2740 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 292 | train 0.4812/1.4953 | val 0.5784/1.4088 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 293 | train 0.4537/1.5425 | val 0.5975/1.3516 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 294 | train 0.4479/1.4937 | val 0.5487/1.4202 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 295 | train 0.4309/1.5460 | val 0.7119/1.2109 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 296 | train 0.4579/1.4994 | val 0.7288/1.1825 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 297 | train 0.4563/1.5109 | val 0.7797/1.1626 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 298 | train 0.4775/1.5404 | val 0.7860/1.1722 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 299 | train 0.4574/1.5382 | val 0.4852/1.5308 | best 0.7966 @ 286

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold3 | ep 300 | train 0.4452/1.5144 | val 0.7458/1.1725 | best 0.7966 @ 286

SWA BN:   0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

SWA (106 snapshots) val acc: 0.7500  |  best ckpt: 0.7966
-> Keeping best checkpoint

  0%|          | 0/25 [00:00<?, ?it/s]

Saved: /home/onyxia/work/tilda-texture-classification/outputs/submissions/submission_seresnet50_bilinear_v3_patch_fold3_tta_labels0.csv
label
0    146
1     91
2    117
3     94
4     50
5     94
6    115
7     82
Name: count, dtype: int64

================================================================================
seresnet50_bilinear_v3_patch | fold 4/5
================================================================================

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 001 | train 0.1133/2.0800 | val 0.1314/2.0785 | best 0.1314 @ 1

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 002 | train 0.1159/2.0816 | val 0.1377/2.0781 | best 0.1377 @ 2

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 003 | train 0.1249/2.0807 | val 0.1441/2.0789 | best 0.1441 @ 3

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 004 | train 0.1281/2.0800 | val 0.1335/2.0789 | best 0.1441 @ 3

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 005 | train 0.1413/2.0742 | val 0.1483/2.0685 | best 0.1483 @ 5

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 006 | train 0.1488/2.0655 | val 0.1886/2.0517 | best 0.1886 @ 6

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 007 | train 0.1747/2.0461 | val 0.1631/2.0735 | best 0.1886 @ 6

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 008 | train 0.1604/2.0346 | val 0.2055/1.9947 | best 0.2055 @ 8

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 009 | train 0.1715/2.0295 | val 0.2034/1.9826 | best 0.2055 @ 8

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 010 | train 0.1758/2.0199 | val 0.2373/1.9612 | best 0.2373 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 011 | train 0.1964/2.0136 | val 0.1843/1.9748 | best 0.2373 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 012 | train 0.1953/1.9712 | val 0.2182/1.9890 | best 0.2373 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 013 | train 0.2017/1.9801 | val 0.2373/1.9528 | best 0.2373 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 014 | train 0.2118/1.9752 | val 0.2458/1.8820 | best 0.2458 @ 14

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 015 | train 0.2049/1.9774 | val 0.2458/1.8881 | best 0.2458 @ 14

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 016 | train 0.2001/1.9646 | val 0.3136/1.8749 | best 0.3136 @ 16

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 017 | train 0.2245/1.9623 | val 0.2055/1.9402 | best 0.3136 @ 16

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 018 | train 0.2292/1.9450 | val 0.3051/1.8514 | best 0.3136 @ 16

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 019 | train 0.2245/1.9348 | val 0.3157/1.8524 | best 0.3157 @ 19

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 020 | train 0.2213/1.9779 | val 0.2987/1.8612 | best 0.3157 @ 19

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 021 | train 0.2345/1.9282 | val 0.2924/1.8189 | best 0.3157 @ 19

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 022 | train 0.2229/1.9532 | val 0.3602/1.8082 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 023 | train 0.2403/1.9331 | val 0.3411/1.8336 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 024 | train 0.2287/1.9196 | val 0.2712/1.8748 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 025 | train 0.2223/1.9353 | val 0.3369/1.8066 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 026 | train 0.2467/1.9352 | val 0.2394/1.8885 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 027 | train 0.2356/1.9377 | val 0.2458/1.9497 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 028 | train 0.2308/1.9314 | val 0.3347/1.7991 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 029 | train 0.2594/1.9147 | val 0.2119/1.9348 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 030 | train 0.2594/1.8950 | val 0.2669/1.8605 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 031 | train 0.2679/1.9000 | val 0.3093/1.8261 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 032 | train 0.2710/1.9078 | val 0.2924/1.7769 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 033 | train 0.2832/1.9063 | val 0.3347/1.8173 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 034 | train 0.2626/1.9220 | val 0.3581/1.7996 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 035 | train 0.2440/1.8926 | val 0.3411/1.7598 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 036 | train 0.2732/1.8915 | val 0.1949/1.9522 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 037 | train 0.2520/1.9055 | val 0.3178/1.8156 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 038 | train 0.2552/1.8956 | val 0.2479/1.8903 | best 0.3602 @ 22

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 039 | train 0.2853/1.8857 | val 0.3686/1.8011 | best 0.3686 @ 39

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 040 | train 0.2737/1.8671 | val 0.3114/1.8499 | best 0.3686 @ 39

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 041 | train 0.2890/1.8787 | val 0.3390/1.7557 | best 0.3686 @ 39

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 042 | train 0.2573/1.8830 | val 0.3708/1.7097 | best 0.3708 @ 42

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 043 | train 0.2636/1.9031 | val 0.3157/1.7629 | best 0.3708 @ 42

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 044 | train 0.2827/1.8736 | val 0.3157/1.8141 | best 0.3708 @ 42

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 045 | train 0.2636/1.8878 | val 0.3835/1.7222 | best 0.3835 @ 45

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 046 | train 0.2753/1.8753 | val 0.2542/1.8745 | best 0.3835 @ 45

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 047 | train 0.2837/1.8764 | val 0.2839/1.8475 | best 0.3835 @ 45

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 048 | train 0.2965/1.8589 | val 0.4131/1.7211 | best 0.4131 @ 48

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 049 | train 0.2647/1.8628 | val 0.3496/1.7461 | best 0.4131 @ 48

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 050 | train 0.2710/1.8657 | val 0.3814/1.7473 | best 0.4131 @ 48

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 051 | train 0.2816/1.8663 | val 0.3496/1.7502 | best 0.4131 @ 48

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 052 | train 0.2721/1.8829 | val 0.3369/1.8211 | best 0.4131 @ 48

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 053 | train 0.2679/1.8810 | val 0.1970/2.1087 | best 0.4131 @ 48

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 054 | train 0.2483/1.8785 | val 0.3517/1.7507 | best 0.4131 @ 48

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 055 | train 0.2620/1.8656 | val 0.3750/1.7373 | best 0.4131 @ 48

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 056 | train 0.2700/1.8510 | val 0.4237/1.7025 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 057 | train 0.2573/1.8612 | val 0.4089/1.7513 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 058 | train 0.2721/1.8563 | val 0.3136/1.8429 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 059 | train 0.2885/1.8829 | val 0.4047/1.7131 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 060 | train 0.2673/1.8965 | val 0.2860/1.8805 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 061 | train 0.3033/1.8586 | val 0.3369/1.7728 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 062 | train 0.3028/1.8389 | val 0.3559/1.7259 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 063 | train 0.2546/1.8365 | val 0.3835/1.7565 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 064 | train 0.2896/1.8523 | val 0.2881/1.9314 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 065 | train 0.3039/1.8633 | val 0.3644/1.7228 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 066 | train 0.2938/1.8499 | val 0.3517/1.7541 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 067 | train 0.2965/1.8544 | val 0.3157/1.8126 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 068 | train 0.3224/1.8230 | val 0.3136/1.7894 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 069 | train 0.2949/1.8598 | val 0.2839/1.8543 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 070 | train 0.2726/1.8359 | val 0.4195/1.6740 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 071 | train 0.2869/1.8344 | val 0.2691/1.8636 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 072 | train 0.2875/1.8069 | val 0.3178/1.8263 | best 0.4237 @ 56

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 073 | train 0.2742/1.8598 | val 0.4386/1.6851 | best 0.4386 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 074 | train 0.3235/1.8227 | val 0.3898/1.7285 | best 0.4386 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 075 | train 0.2800/1.8601 | val 0.2669/1.8803 | best 0.4386 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 076 | train 0.2732/1.8444 | val 0.3093/1.8745 | best 0.4386 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 077 | train 0.2965/1.8296 | val 0.3941/1.7446 | best 0.4386 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 078 | train 0.2663/1.7946 | val 0.4004/1.6758 | best 0.4386 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 079 | train 0.3002/1.8330 | val 0.3263/1.7648 | best 0.4386 @ 73

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 080 | train 0.2901/1.8202 | val 0.4428/1.6404 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 081 | train 0.3033/1.8250 | val 0.3220/1.8912 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 082 | train 0.3007/1.8216 | val 0.3411/1.7355 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 083 | train 0.2726/1.8429 | val 0.3750/1.7346 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 084 | train 0.3060/1.8177 | val 0.2606/1.8507 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 085 | train 0.2822/1.8333 | val 0.3792/1.6927 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 086 | train 0.2996/1.8263 | val 0.4237/1.6871 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 087 | train 0.2769/1.8494 | val 0.3962/1.7082 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 088 | train 0.2689/1.8352 | val 0.4068/1.7031 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 089 | train 0.2732/1.8528 | val 0.4025/1.6972 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 090 | train 0.3240/1.7805 | val 0.3432/1.7352 | best 0.4428 @ 80

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 091 | train 0.3012/1.7792 | val 0.4894/1.6205 | best 0.4894 @ 91

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 092 | train 0.3002/1.8097 | val 0.3898/1.7955 | best 0.4894 @ 91

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 093 | train 0.2652/1.8540 | val 0.4958/1.6197 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 094 | train 0.3092/1.8349 | val 0.3686/1.7418 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 095 | train 0.3081/1.7863 | val 0.3814/1.6918 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 096 | train 0.3383/1.8107 | val 0.4555/1.6627 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 097 | train 0.3097/1.8179 | val 0.4852/1.6279 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 098 | train 0.2927/1.8500 | val 0.4047/1.7189 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 099 | train 0.2811/1.8043 | val 0.3305/1.8439 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 100 | train 0.2938/1.8221 | val 0.4195/1.6622 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 101 | train 0.3272/1.8113 | val 0.4280/1.6735 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 102 | train 0.2965/1.7764 | val 0.3559/1.7180 | best 0.4958 @ 93

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 103 | train 0.2896/1.7936 | val 0.5148/1.6049 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 104 | train 0.3346/1.7972 | val 0.4746/1.6194 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 105 | train 0.3086/1.7969 | val 0.4322/1.6860 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 106 | train 0.3086/1.7863 | val 0.4364/1.6681 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 107 | train 0.3245/1.7899 | val 0.4322/1.6506 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 108 | train 0.2927/1.7821 | val 0.4195/1.6657 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 109 | train 0.2689/1.8158 | val 0.4343/1.6650 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 110 | train 0.3129/1.8085 | val 0.5148/1.5290 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 111 | train 0.3028/1.8097 | val 0.4258/1.6951 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 112 | train 0.2959/1.7805 | val 0.2500/1.9126 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 113 | train 0.3160/1.7924 | val 0.4809/1.5843 | best 0.5148 @ 103

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 114 | train 0.3293/1.7786 | val 0.5212/1.5295 | best 0.5212 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 115 | train 0.3483/1.7808 | val 0.4788/1.5993 | best 0.5212 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 116 | train 0.3187/1.7901 | val 0.3919/1.6621 | best 0.5212 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 117 | train 0.3224/1.7754 | val 0.4915/1.5951 | best 0.5212 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 118 | train 0.3256/1.7933 | val 0.4343/1.6483 | best 0.5212 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 119 | train 0.3282/1.7645 | val 0.5000/1.5642 | best 0.5212 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 120 | train 0.3452/1.7596 | val 0.4873/1.6342 | best 0.5212 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 121 | train 0.3208/1.7626 | val 0.3242/1.8246 | best 0.5212 @ 114

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 122 | train 0.3377/1.8110 | val 0.5403/1.5234 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 123 | train 0.3261/1.7559 | val 0.3432/1.8198 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 124 | train 0.2996/1.8441 | val 0.5339/1.5462 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 125 | train 0.3208/1.7813 | val 0.4216/1.6712 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 126 | train 0.3383/1.7665 | val 0.4619/1.6372 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 127 | train 0.2695/1.8275 | val 0.4343/1.6469 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 128 | train 0.3589/1.7353 | val 0.4534/1.6763 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 129 | train 0.3086/1.7342 | val 0.4555/1.5979 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 130 | train 0.3647/1.7502 | val 0.4555/1.6334 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 131 | train 0.3261/1.7636 | val 0.4153/1.6967 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 132 | train 0.3049/1.7721 | val 0.3390/1.7948 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 133 | train 0.3081/1.7601 | val 0.3475/1.8113 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 134 | train 0.3356/1.7493 | val 0.4746/1.6082 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 135 | train 0.3420/1.7782 | val 0.3008/1.8699 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 136 | train 0.3314/1.7839 | val 0.5297/1.5626 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 137 | train 0.3626/1.7677 | val 0.4682/1.5846 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 138 | train 0.3351/1.7646 | val 0.3771/1.7323 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 139 | train 0.3399/1.7693 | val 0.3432/1.8591 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 140 | train 0.3653/1.7256 | val 0.3538/1.7919 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 141 | train 0.3452/1.7460 | val 0.4979/1.5572 | best 0.5403 @ 122

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 142 | train 0.3573/1.7283 | val 0.5593/1.4950 | best 0.5593 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 143 | train 0.3272/1.7156 | val 0.4280/1.7497 | best 0.5593 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 144 | train 0.3489/1.7569 | val 0.4174/1.6893 | best 0.5593 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 145 | train 0.3383/1.7609 | val 0.5233/1.5381 | best 0.5593 @ 142

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 146 | train 0.3425/1.7652 | val 0.5614/1.5123 | best 0.5614 @ 146

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 147 | train 0.3531/1.7273 | val 0.4619/1.6307 | best 0.5614 @ 146

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 148 | train 0.3457/1.7556 | val 0.4915/1.5783 | best 0.5614 @ 146

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 149 | train 0.3118/1.7569 | val 0.4343/1.6674 | best 0.5614 @ 146

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 150 | train 0.3489/1.7150 | val 0.4915/1.5911 | best 0.5614 @ 146

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 151 | train 0.3944/1.6874 | val 0.2606/2.0668 | best 0.5614 @ 146

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 152 | train 0.3266/1.7040 | val 0.3792/1.7205 | best 0.5614 @ 146

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 153 | train 0.2917/1.7618 | val 0.5360/1.5119 | best 0.5614 @ 146

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 154 | train 0.3722/1.6957 | val 0.5932/1.4507 | best 0.5932 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 155 | train 0.3616/1.7172 | val 0.5932/1.4383 | best 0.5932 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 156 | train 0.3536/1.7354 | val 0.5042/1.5554 | best 0.5932 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 157 | train 0.3647/1.6944 | val 0.3157/1.8360 | best 0.5932 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 158 | train 0.3457/1.7521 | val 0.4068/1.6695 | best 0.5932 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 159 | train 0.3272/1.7830 | val 0.4025/1.6762 | best 0.5932 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 160 | train 0.3817/1.6951 | val 0.4682/1.5836 | best 0.5932 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 161 | train 0.3192/1.7113 | val 0.4894/1.5937 | best 0.5932 @ 154

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 162 | train 0.4013/1.6272 | val 0.6081/1.4086 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 163 | train 0.3674/1.6937 | val 0.3517/1.8772 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 164 | train 0.3727/1.6616 | val 0.5805/1.4302 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 165 | train 0.3563/1.7144 | val 0.5784/1.4391 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 166 | train 0.4166/1.6639 | val 0.5021/1.5284 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 167 | train 0.3589/1.7138 | val 0.5318/1.5236 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 168 | train 0.3547/1.7078 | val 0.5127/1.4889 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 169 | train 0.3743/1.7263 | val 0.4131/1.6782 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 170 | train 0.3891/1.6844 | val 0.5403/1.5771 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 171 | train 0.3690/1.7041 | val 0.5932/1.4819 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 172 | train 0.3542/1.7193 | val 0.5106/1.5225 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 173 | train 0.3356/1.7220 | val 0.5042/1.5501 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 174 | train 0.3060/1.7656 | val 0.4364/1.6363 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 175 | train 0.3796/1.6791 | val 0.4788/1.5771 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 176 | train 0.3669/1.6330 | val 0.4534/1.6181 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 177 | train 0.3489/1.6968 | val 0.5699/1.4790 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 178 | train 0.3759/1.6657 | val 0.5805/1.4673 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 179 | train 0.4071/1.6784 | val 0.3877/1.8079 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 180 | train 0.4023/1.6901 | val 0.6038/1.4519 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 181 | train 0.3277/1.7270 | val 0.5572/1.5318 | best 0.6081 @ 162

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 182 | train 0.3303/1.7503 | val 0.6123/1.4354 | best 0.6123 @ 182

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 183 | train 0.3610/1.6583 | val 0.5551/1.4410 | best 0.6123 @ 182

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 184 | train 0.3827/1.6479 | val 0.3962/1.8130 | best 0.6123 @ 182

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 185 | train 0.3817/1.6630 | val 0.5763/1.4629 | best 0.6123 @ 182

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 186 | train 0.4198/1.6498 | val 0.5975/1.4156 | best 0.6123 @ 182

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 187 | train 0.3801/1.6644 | val 0.6123/1.4028 | best 0.6123 @ 182

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 188 | train 0.3393/1.6960 | val 0.4640/1.5610 | best 0.6123 @ 182

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 189 | train 0.3478/1.6837 | val 0.6314/1.3987 | best 0.6314 @ 189

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 190 | train 0.3404/1.6941 | val 0.3877/1.7707 | best 0.6314 @ 189

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 191 | train 0.3806/1.7100 | val 0.6165/1.4110 | best 0.6314 @ 189

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 192 | train 0.3404/1.6861 | val 0.6483/1.3493 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 193 | train 0.3711/1.6529 | val 0.6419/1.3617 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 194 | train 0.3425/1.6718 | val 0.5191/1.4768 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 195 | train 0.3436/1.7008 | val 0.5593/1.4683 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 196 | train 0.3669/1.6703 | val 0.4513/1.6494 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 197 | train 0.3859/1.6797 | val 0.5805/1.4404 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 198 | train 0.3526/1.6625 | val 0.4343/1.6907 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 199 | train 0.3674/1.6678 | val 0.5530/1.4785 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 200 | train 0.3769/1.6365 | val 0.3856/1.7810 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 201 | train 0.3616/1.6699 | val 0.6102/1.3940 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 202 | train 0.4479/1.5809 | val 0.6102/1.3915 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 203 | train 0.4198/1.6587 | val 0.5657/1.5084 | best 0.6483 @ 192

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 204 | train 0.3743/1.6950 | val 0.6992/1.3339 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 205 | train 0.3409/1.6788 | val 0.6038/1.3914 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 206 | train 0.3896/1.6124 | val 0.5847/1.4008 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 207 | train 0.4272/1.5872 | val 0.3559/1.7895 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 208 | train 0.4367/1.6399 | val 0.6504/1.3759 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 209 | train 0.3764/1.6409 | val 0.5403/1.5031 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 210 | train 0.3737/1.6453 | val 0.5572/1.4850 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 211 | train 0.4352/1.5980 | val 0.5826/1.4494 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 212 | train 0.3939/1.6286 | val 0.6610/1.3258 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 213 | train 0.3801/1.6432 | val 0.6123/1.3978 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 214 | train 0.3732/1.6510 | val 0.3983/1.7329 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 215 | train 0.3843/1.6181 | val 0.3602/1.8139 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 216 | train 0.3547/1.6969 | val 0.5678/1.4303 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 217 | train 0.4256/1.5750 | val 0.5593/1.4337 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 218 | train 0.4553/1.6115 | val 0.5953/1.3867 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 219 | train 0.4007/1.6617 | val 0.5360/1.4861 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 220 | train 0.4314/1.5972 | val 0.6716/1.2883 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 221 | train 0.4029/1.5817 | val 0.5551/1.4706 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 222 | train 0.3282/1.6835 | val 0.5339/1.4516 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 223 | train 0.3854/1.6314 | val 0.6822/1.3021 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 224 | train 0.3785/1.6381 | val 0.6165/1.3759 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 225 | train 0.4510/1.5608 | val 0.5699/1.4088 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 226 | train 0.4134/1.5907 | val 0.5085/1.5756 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 227 | train 0.4156/1.6015 | val 0.6398/1.3188 | best 0.6992 @ 204

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 228 | train 0.4002/1.6355 | val 0.7394/1.2587 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 229 | train 0.3753/1.6184 | val 0.7352/1.2367 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 230 | train 0.4209/1.5636 | val 0.6123/1.3583 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 231 | train 0.4172/1.5840 | val 0.6441/1.3526 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 232 | train 0.4246/1.5966 | val 0.6102/1.3871 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 233 | train 0.4018/1.6172 | val 0.5424/1.4910 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 234 | train 0.4341/1.6256 | val 0.6631/1.2918 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 235 | train 0.4082/1.5805 | val 0.5763/1.4063 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 236 | train 0.3896/1.5826 | val 0.6907/1.2724 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 237 | train 0.4055/1.6087 | val 0.6589/1.3037 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 238 | train 0.4029/1.6207 | val 0.6292/1.3875 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 239 | train 0.4309/1.5867 | val 0.6208/1.3356 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 240 | train 0.3960/1.5305 | val 0.6737/1.2876 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 241 | train 0.4087/1.5495 | val 0.6631/1.3096 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 242 | train 0.4150/1.6247 | val 0.6589/1.3029 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 243 | train 0.4203/1.4850 | val 0.6907/1.2528 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 244 | train 0.4468/1.5497 | val 0.4047/1.7223 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 245 | train 0.4288/1.5516 | val 0.6102/1.3561 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 246 | train 0.4087/1.5945 | val 0.6123/1.3743 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 247 | train 0.4330/1.5740 | val 0.5784/1.4121 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 248 | train 0.3684/1.5902 | val 0.6822/1.2342 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 249 | train 0.3647/1.5779 | val 0.6525/1.3018 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 250 | train 0.4473/1.6050 | val 0.7352/1.1803 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 251 | train 0.3753/1.5435 | val 0.6547/1.3340 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 252 | train 0.4420/1.5647 | val 0.7097/1.2435 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 253 | train 0.4124/1.5880 | val 0.7119/1.2196 | best 0.7394 @ 228

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 254 | train 0.4547/1.5632 | val 0.7436/1.2095 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 255 | train 0.4246/1.5988 | val 0.5021/1.5350 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 256 | train 0.4140/1.5430 | val 0.6737/1.2668 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 257 | train 0.4373/1.5501 | val 0.6864/1.2583 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 258 | train 0.4156/1.5985 | val 0.5699/1.3807 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 259 | train 0.3992/1.5799 | val 0.6674/1.2636 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 260 | train 0.4839/1.4926 | val 0.5530/1.4804 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 261 | train 0.3997/1.5850 | val 0.7161/1.2251 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 262 | train 0.4484/1.5686 | val 0.6949/1.2506 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 263 | train 0.4738/1.5491 | val 0.3517/1.8298 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 264 | train 0.4346/1.5501 | val 0.7013/1.2408 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 265 | train 0.4653/1.4842 | val 0.6907/1.2726 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 266 | train 0.4399/1.6202 | val 0.5975/1.3829 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 267 | train 0.4611/1.5449 | val 0.7013/1.2212 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 268 | train 0.4627/1.5151 | val 0.7225/1.2119 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 269 | train 0.4510/1.5581 | val 0.6695/1.2888 | best 0.7436 @ 254

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 270 | train 0.4341/1.5118 | val 0.7627/1.1561 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 271 | train 0.4262/1.5436 | val 0.6356/1.2929 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 272 | train 0.4410/1.5247 | val 0.6907/1.2173 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 273 | train 0.4717/1.5496 | val 0.6780/1.2797 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 274 | train 0.4701/1.5468 | val 0.4979/1.5291 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 275 | train 0.4447/1.5034 | val 0.3390/1.9534 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 276 | train 0.4489/1.5199 | val 0.6886/1.2432 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 277 | train 0.3981/1.5059 | val 0.6970/1.2101 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 278 | train 0.4304/1.5717 | val 0.7076/1.2344 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 279 | train 0.4352/1.5612 | val 0.6780/1.2248 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 280 | train 0.4436/1.5418 | val 0.7225/1.1952 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 281 | train 0.4457/1.5468 | val 0.7585/1.1574 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 282 | train 0.4071/1.5431 | val 0.6059/1.3590 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 283 | train 0.4500/1.5308 | val 0.5085/1.4969 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 284 | train 0.4547/1.5277 | val 0.7246/1.2076 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 285 | train 0.4743/1.5131 | val 0.6335/1.3437 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 286 | train 0.4246/1.5091 | val 0.6653/1.2588 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 287 | train 0.4399/1.5147 | val 0.7331/1.1813 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 288 | train 0.5077/1.4693 | val 0.7373/1.1935 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 289 | train 0.4574/1.5174 | val 0.6631/1.2893 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 290 | train 0.4203/1.5034 | val 0.7436/1.1750 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 291 | train 0.4521/1.5430 | val 0.4619/1.5859 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 292 | train 0.4664/1.5098 | val 0.6822/1.2359 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 293 | train 0.4717/1.4597 | val 0.7034/1.2042 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 294 | train 0.4553/1.5253 | val 0.7097/1.2332 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 295 | train 0.4749/1.5342 | val 0.7013/1.2150 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 296 | train 0.4701/1.5456 | val 0.6377/1.3332 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 297 | train 0.4590/1.5144 | val 0.6970/1.2296 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 298 | train 0.4336/1.5666 | val 0.7119/1.2102 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 299 | train 0.4272/1.5028 | val 0.7542/1.1683 | best 0.7627 @ 270

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold4 | ep 300 | train 0.4786/1.4823 | val 0.6165/1.3209 | best 0.7627 @ 270

SWA BN:   0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

SWA (106 snapshots) val acc: 0.7648  |  best ckpt: 0.7627
-> SWA model saved as best

  0%|          | 0/25 [00:00<?, ?it/s]

Saved: /home/onyxia/work/tilda-texture-classification/outputs/submissions/submission_seresnet50_bilinear_v3_patch_fold4_tta_labels0.csv
label
0    168
1     80
2    117
3    106
4     52
5     85
6    103
7     78
Name: count, dtype: int64

================================================================================
seresnet50_bilinear_v3_patch | fold 5/5
================================================================================

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 001 | train 0.1075/2.0802 | val 0.1356/2.0786 | best 0.1356 @ 1

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 002 | train 0.1233/2.0808 | val 0.1271/2.0780 | best 0.1356 @ 1

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 003 | train 0.1265/2.0813 | val 0.1864/2.0747 | best 0.1864 @ 3

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 004 | train 0.1223/2.0811 | val 0.1441/2.0756 | best 0.1864 @ 3

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 005 | train 0.1493/2.0759 | val 0.1377/2.0704 | best 0.1864 @ 3

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 006 | train 0.1382/2.0688 | val 0.1822/2.0495 | best 0.1864 @ 3

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 007 | train 0.1588/2.0532 | val 0.2182/2.0034 | best 0.2182 @ 7

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 008 | train 0.1800/2.0359 | val 0.2161/1.9841 | best 0.2182 @ 7

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 009 | train 0.1641/2.0355 | val 0.2436/1.9463 | best 0.2436 @ 9

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 010 | train 0.1768/2.0249 | val 0.2669/1.9593 | best 0.2669 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 011 | train 0.1763/2.0107 | val 0.2076/1.9364 | best 0.2669 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 012 | train 0.1900/2.0044 | val 0.1504/2.0399 | best 0.2669 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 013 | train 0.2170/1.9799 | val 0.2669/1.8865 | best 0.2669 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 014 | train 0.2139/1.9701 | val 0.2140/1.9192 | best 0.2669 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 015 | train 0.2059/1.9805 | val 0.2585/1.8857 | best 0.2669 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 016 | train 0.2123/1.9823 | val 0.1907/2.0163 | best 0.2669 @ 10

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 017 | train 0.2033/1.9746 | val 0.3305/1.8769 | best 0.3305 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 018 | train 0.1900/1.9850 | val 0.3030/1.9016 | best 0.3305 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 019 | train 0.2239/1.9504 | val 0.2458/1.9303 | best 0.3305 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 020 | train 0.2049/1.9549 | val 0.2903/1.8591 | best 0.3305 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 021 | train 0.2308/1.9566 | val 0.3220/1.8035 | best 0.3305 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 022 | train 0.2197/1.9266 | val 0.3242/1.8130 | best 0.3305 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 023 | train 0.2515/1.9266 | val 0.3242/1.8366 | best 0.3305 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 024 | train 0.2229/1.9383 | val 0.2987/1.8192 | best 0.3305 @ 17

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 025 | train 0.2155/1.9110 | val 0.3686/1.7782 | best 0.3686 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 026 | train 0.2483/1.9120 | val 0.3093/1.7934 | best 0.3686 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 027 | train 0.2319/1.9271 | val 0.3136/1.8151 | best 0.3686 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 028 | train 0.2520/1.9248 | val 0.2606/1.9703 | best 0.3686 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 029 | train 0.2557/1.8940 | val 0.3157/1.8047 | best 0.3686 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 030 | train 0.2509/1.9085 | val 0.2691/1.9392 | best 0.3686 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 031 | train 0.2308/1.9101 | val 0.3199/1.8211 | best 0.3686 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 032 | train 0.2298/1.9105 | val 0.2669/1.8446 | best 0.3686 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 033 | train 0.2578/1.8988 | val 0.2458/1.9311 | best 0.3686 @ 25

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 034 | train 0.2266/1.9070 | val 0.3729/1.7406 | best 0.3729 @ 34

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 035 | train 0.2361/1.9140 | val 0.3326/1.8388 | best 0.3729 @ 34

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 036 | train 0.2462/1.9034 | val 0.3411/1.7975 | best 0.3729 @ 34

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 037 | train 0.2467/1.9065 | val 0.3347/1.8272 | best 0.3729 @ 34

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 038 | train 0.2626/1.8895 | val 0.3475/1.7672 | best 0.3729 @ 34

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 039 | train 0.2541/1.8819 | val 0.3284/1.7887 | best 0.3729 @ 34

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 040 | train 0.2372/1.8959 | val 0.2987/1.8812 | best 0.3729 @ 34

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 041 | train 0.2758/1.8691 | val 0.3771/1.7154 | best 0.3771 @ 41

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 042 | train 0.2451/1.9116 | val 0.3856/1.7004 | best 0.3856 @ 42

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 043 | train 0.2271/1.8712 | val 0.3898/1.6876 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 044 | train 0.2599/1.8893 | val 0.3263/1.7667 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 045 | train 0.2605/1.8728 | val 0.3602/1.7476 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 046 | train 0.2583/1.8921 | val 0.2627/1.8468 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 047 | train 0.2520/1.9049 | val 0.3030/1.7924 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 048 | train 0.2435/1.8821 | val 0.3792/1.7115 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 049 | train 0.2657/1.9070 | val 0.3750/1.7190 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 050 | train 0.2890/1.8813 | val 0.2775/1.9385 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 051 | train 0.2795/1.9127 | val 0.3623/1.7641 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 052 | train 0.2335/1.8678 | val 0.2436/1.8908 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 053 | train 0.2774/1.8646 | val 0.3771/1.7070 | best 0.3898 @ 43

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 054 | train 0.2896/1.8768 | val 0.4322/1.6896 | best 0.4322 @ 54

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 055 | train 0.2292/1.8862 | val 0.3411/1.8112 | best 0.4322 @ 54

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 056 | train 0.2594/1.8719 | val 0.3411/1.7183 | best 0.4322 @ 54

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 057 | train 0.3224/1.8477 | val 0.3750/1.7497 | best 0.4322 @ 54

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 058 | train 0.2726/1.8676 | val 0.3051/1.8209 | best 0.4322 @ 54

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 059 | train 0.2933/1.8715 | val 0.4703/1.6554 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 060 | train 0.2689/1.8316 | val 0.3220/1.8386 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 061 | train 0.2790/1.8533 | val 0.4174/1.6736 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 062 | train 0.2657/1.8707 | val 0.3898/1.6979 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 063 | train 0.2853/1.8901 | val 0.3305/1.7696 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 064 | train 0.2716/1.8664 | val 0.4258/1.7001 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 065 | train 0.3187/1.8492 | val 0.3665/1.7868 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 066 | train 0.2557/1.8666 | val 0.3114/1.8134 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 067 | train 0.2589/1.8538 | val 0.3665/1.7668 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 068 | train 0.2742/1.8768 | val 0.3496/1.7664 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 069 | train 0.2705/1.8463 | val 0.4449/1.6736 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 070 | train 0.2790/1.8644 | val 0.4449/1.6729 | best 0.4703 @ 59

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 071 | train 0.2912/1.8414 | val 0.4788/1.6618 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 072 | train 0.2626/1.8725 | val 0.3517/1.8062 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 073 | train 0.2705/1.8572 | val 0.3263/1.8485 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 074 | train 0.2785/1.8404 | val 0.3305/1.8060 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 075 | train 0.2541/1.8792 | val 0.3559/1.7849 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 076 | train 0.2975/1.8664 | val 0.3665/1.7466 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 077 | train 0.2927/1.8443 | val 0.4216/1.6945 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 078 | train 0.2843/1.8402 | val 0.3877/1.6886 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 079 | train 0.3044/1.8225 | val 0.4449/1.6368 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 080 | train 0.2705/1.8260 | val 0.3771/1.6560 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 081 | train 0.2726/1.8593 | val 0.3602/1.8170 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 082 | train 0.2726/1.8378 | val 0.4513/1.6598 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 083 | train 0.2673/1.8293 | val 0.3856/1.7300 | best 0.4788 @ 71

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 084 | train 0.2885/1.8388 | val 0.4979/1.6340 | best 0.4979 @ 84

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 085 | train 0.2912/1.7865 | val 0.4068/1.7089 | best 0.4979 @ 84

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 086 | train 0.2938/1.8609 | val 0.3665/1.7852 | best 0.4979 @ 84

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 087 | train 0.2758/1.8732 | val 0.4237/1.6677 | best 0.4979 @ 84

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 088 | train 0.2996/1.8167 | val 0.3877/1.7164 | best 0.4979 @ 84

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 089 | train 0.2996/1.8093 | val 0.5254/1.5631 | best 0.5254 @ 89

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 090 | train 0.2943/1.8585 | val 0.5275/1.5562 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 091 | train 0.2901/1.8297 | val 0.4470/1.6590 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 092 | train 0.2959/1.8215 | val 0.4025/1.6435 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 093 | train 0.3065/1.7966 | val 0.3305/1.7726 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 094 | train 0.2965/1.8313 | val 0.3093/1.9606 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 095 | train 0.2790/1.8172 | val 0.3665/1.7126 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 096 | train 0.2785/1.7833 | val 0.3877/1.7288 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 097 | train 0.3150/1.8128 | val 0.3072/1.8091 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 098 | train 0.2869/1.8119 | val 0.4809/1.6049 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 099 | train 0.3023/1.7876 | val 0.3305/1.8546 | best 0.5275 @ 90

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 100 | train 0.2959/1.8382 | val 0.5318/1.5754 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 101 | train 0.2742/1.8245 | val 0.3453/1.7545 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 102 | train 0.3113/1.8078 | val 0.4703/1.5723 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 103 | train 0.3160/1.8278 | val 0.2733/2.0505 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 104 | train 0.3467/1.8061 | val 0.3898/1.8145 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 105 | train 0.2954/1.8303 | val 0.3517/1.9052 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 106 | train 0.2954/1.8256 | val 0.3496/1.7349 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 107 | train 0.2996/1.8084 | val 0.4386/1.7373 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 108 | train 0.3134/1.7871 | val 0.4364/1.6359 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 109 | train 0.3229/1.7952 | val 0.3432/1.7895 | best 0.5318 @ 100

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 110 | train 0.2933/1.8228 | val 0.5487/1.5227 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 111 | train 0.3123/1.8206 | val 0.4746/1.6194 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 112 | train 0.3060/1.7834 | val 0.5403/1.5167 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 113 | train 0.3145/1.7948 | val 0.2987/1.8028 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 114 | train 0.3166/1.7735 | val 0.4492/1.6112 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 115 | train 0.3150/1.8024 | val 0.3941/1.7001 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 116 | train 0.3002/1.7961 | val 0.3178/1.7682 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 117 | train 0.3150/1.7947 | val 0.5021/1.5248 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 118 | train 0.3118/1.8255 | val 0.3771/1.7306 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 119 | train 0.2975/1.7954 | val 0.5106/1.5432 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 120 | train 0.3314/1.8080 | val 0.3347/1.7740 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 121 | train 0.3245/1.7793 | val 0.4831/1.5956 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 122 | train 0.3176/1.8021 | val 0.4089/1.6628 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 123 | train 0.2785/1.7701 | val 0.3835/1.6974 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 124 | train 0.3446/1.7991 | val 0.4682/1.6436 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 125 | train 0.2811/1.7567 | val 0.4873/1.5977 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 126 | train 0.2922/1.7746 | val 0.4767/1.5790 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 127 | train 0.3573/1.7719 | val 0.5169/1.5302 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 128 | train 0.3070/1.7510 | val 0.3877/1.7128 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 129 | train 0.3462/1.7841 | val 0.3814/1.7065 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 130 | train 0.3393/1.7613 | val 0.2860/1.9271 | best 0.5487 @ 110

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 131 | train 0.3235/1.7626 | val 0.5996/1.4598 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 132 | train 0.3637/1.7289 | val 0.4025/1.8000 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 133 | train 0.2980/1.8174 | val 0.3898/1.7025 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 134 | train 0.3372/1.7698 | val 0.5148/1.5516 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 135 | train 0.3155/1.7696 | val 0.5000/1.5271 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 136 | train 0.3139/1.7538 | val 0.3877/1.6849 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 137 | train 0.3076/1.7867 | val 0.5487/1.4826 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 138 | train 0.3584/1.7337 | val 0.5318/1.5269 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 139 | train 0.3404/1.7903 | val 0.3390/1.9185 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 140 | train 0.2996/1.7863 | val 0.4682/1.5722 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 141 | train 0.3346/1.7713 | val 0.4682/1.6087 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 142 | train 0.3060/1.7888 | val 0.3729/1.8041 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 143 | train 0.3790/1.7454 | val 0.4979/1.6110 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 144 | train 0.3367/1.7291 | val 0.3051/1.8601 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 145 | train 0.3256/1.7391 | val 0.4915/1.5791 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 146 | train 0.3017/1.7895 | val 0.5042/1.5633 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 147 | train 0.3065/1.7779 | val 0.4364/1.6925 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 148 | train 0.3235/1.7720 | val 0.5530/1.5112 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 149 | train 0.3632/1.7430 | val 0.4936/1.5881 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 150 | train 0.3393/1.7590 | val 0.5466/1.4645 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 151 | train 0.3203/1.7664 | val 0.5657/1.5040 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 152 | train 0.3224/1.7334 | val 0.5127/1.5139 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 153 | train 0.3388/1.7653 | val 0.4089/1.6370 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 154 | train 0.3060/1.7691 | val 0.4492/1.6302 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 155 | train 0.3896/1.7167 | val 0.5784/1.4693 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 156 | train 0.3033/1.7751 | val 0.4068/1.6842 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 157 | train 0.3399/1.7742 | val 0.5593/1.4780 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 158 | train 0.3695/1.7354 | val 0.5636/1.4716 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 159 | train 0.3790/1.7252 | val 0.5254/1.5232 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 160 | train 0.3626/1.7290 | val 0.4576/1.6277 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 161 | train 0.3377/1.6918 | val 0.5233/1.5167 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 162 | train 0.3393/1.7430 | val 0.4576/1.5951 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 163 | train 0.3499/1.6942 | val 0.5551/1.4424 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 164 | train 0.3362/1.7484 | val 0.5742/1.4646 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 165 | train 0.3626/1.7147 | val 0.5763/1.4717 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 166 | train 0.4018/1.6714 | val 0.3093/1.9674 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 167 | train 0.3388/1.7341 | val 0.3835/1.7721 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 168 | train 0.3504/1.7261 | val 0.5169/1.5044 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 169 | train 0.3213/1.7412 | val 0.5212/1.5388 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 170 | train 0.3531/1.7216 | val 0.5064/1.6038 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 171 | train 0.3917/1.7285 | val 0.4746/1.6001 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 172 | train 0.3743/1.6774 | val 0.4915/1.5109 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 173 | train 0.3939/1.6795 | val 0.5318/1.5267 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 174 | train 0.4018/1.6977 | val 0.4640/1.6550 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 175 | train 0.3600/1.7010 | val 0.5869/1.4082 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 176 | train 0.3912/1.6802 | val 0.4449/1.6426 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 177 | train 0.3436/1.6905 | val 0.5381/1.4777 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 178 | train 0.3732/1.7162 | val 0.5508/1.4544 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 179 | train 0.3838/1.7182 | val 0.4958/1.6240 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 180 | train 0.3446/1.7284 | val 0.5021/1.5111 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 181 | train 0.3208/1.6729 | val 0.4767/1.5698 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 182 | train 0.3759/1.7021 | val 0.3072/1.9151 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 183 | train 0.3573/1.7026 | val 0.5127/1.5373 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 184 | train 0.3669/1.7259 | val 0.5212/1.5418 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 185 | train 0.4119/1.6505 | val 0.4852/1.5777 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 186 | train 0.3859/1.7135 | val 0.5593/1.4875 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 187 | train 0.3642/1.6947 | val 0.5996/1.4460 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 188 | train 0.3663/1.6929 | val 0.5275/1.4705 | best 0.5996 @ 131

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 189 | train 0.3076/1.7127 | val 0.6419/1.3586 | best 0.6419 @ 189

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 190 | train 0.3864/1.6703 | val 0.6441/1.3562 | best 0.6441 @ 190

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 191 | train 0.3690/1.6916 | val 0.6229/1.3589 | best 0.6441 @ 190

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 192 | train 0.3594/1.6569 | val 0.4174/1.6758 | best 0.6441 @ 190

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 193 | train 0.3626/1.6423 | val 0.6462/1.3334 | best 0.6462 @ 193

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 194 | train 0.3462/1.6804 | val 0.4492/1.6239 | best 0.6462 @ 193

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 195 | train 0.4156/1.6797 | val 0.5487/1.4989 | best 0.6462 @ 193

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 196 | train 0.3372/1.7060 | val 0.5297/1.5385 | best 0.6462 @ 193

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 197 | train 0.3309/1.6790 | val 0.6123/1.4039 | best 0.6462 @ 193

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 198 | train 0.4071/1.6515 | val 0.5932/1.5015 | best 0.6462 @ 193

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 199 | train 0.3880/1.7079 | val 0.2606/1.9693 | best 0.6462 @ 193

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 200 | train 0.3388/1.6846 | val 0.6547/1.3631 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 201 | train 0.3992/1.6220 | val 0.5847/1.4524 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 202 | train 0.3875/1.6862 | val 0.5636/1.4603 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 203 | train 0.3674/1.6249 | val 0.5551/1.4274 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 204 | train 0.3367/1.7019 | val 0.6525/1.3557 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 205 | train 0.3441/1.6842 | val 0.5254/1.5255 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 206 | train 0.3404/1.6424 | val 0.5996/1.3986 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 207 | train 0.3864/1.6251 | val 0.5169/1.5428 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 208 | train 0.3949/1.6353 | val 0.4025/1.6816 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 209 | train 0.4166/1.6260 | val 0.5614/1.4353 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 210 | train 0.3674/1.6305 | val 0.3771/1.8089 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 211 | train 0.3907/1.6720 | val 0.6504/1.3115 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 212 | train 0.3997/1.6221 | val 0.5847/1.4042 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 213 | train 0.4013/1.6678 | val 0.6441/1.3351 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 214 | train 0.4288/1.6618 | val 0.6314/1.3701 | best 0.6547 @ 200

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 215 | train 0.4320/1.5988 | val 0.6758/1.3085 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 216 | train 0.3642/1.6331 | val 0.3856/1.6970 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 217 | train 0.3467/1.6414 | val 0.5805/1.4082 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 218 | train 0.4293/1.6081 | val 0.5021/1.5252 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 219 | train 0.3674/1.6771 | val 0.6292/1.3636 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 220 | train 0.4288/1.6190 | val 0.5826/1.4867 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 221 | train 0.3780/1.5980 | val 0.5233/1.4959 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 222 | train 0.4209/1.6313 | val 0.6525/1.3512 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 223 | train 0.4341/1.5982 | val 0.6589/1.3033 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 224 | train 0.4071/1.6940 | val 0.6441/1.3350 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 225 | train 0.4050/1.6320 | val 0.5169/1.5063 | best 0.6758 @ 215

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 226 | train 0.4034/1.6250 | val 0.6886/1.2914 | best 0.6886 @ 226

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 227 | train 0.3896/1.6310 | val 0.6631/1.2904 | best 0.6886 @ 226

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 228 | train 0.4246/1.6152 | val 0.5678/1.4119 | best 0.6886 @ 226

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 229 | train 0.3616/1.6674 | val 0.6271/1.3521 | best 0.6886 @ 226

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 230 | train 0.4664/1.6050 | val 0.6038/1.3672 | best 0.6886 @ 226

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 231 | train 0.4187/1.6087 | val 0.5021/1.5112 | best 0.6886 @ 226

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 232 | train 0.4362/1.5855 | val 0.5551/1.4901 | best 0.6886 @ 226

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 233 | train 0.4457/1.5034 | val 0.5720/1.4583 | best 0.6886 @ 226

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 234 | train 0.4230/1.6252 | val 0.6992/1.2535 | best 0.6992 @ 234

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 235 | train 0.4034/1.6054 | val 0.6059/1.3849 | best 0.6992 @ 234

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 236 | train 0.3976/1.5719 | val 0.6801/1.3346 | best 0.6992 @ 234

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 237 | train 0.3827/1.5716 | val 0.6017/1.3852 | best 0.6992 @ 234

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 238 | train 0.4082/1.6166 | val 0.5233/1.4307 | best 0.6992 @ 234

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 239 | train 0.4002/1.6093 | val 0.6271/1.3840 | best 0.6992 @ 234

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 240 | train 0.3785/1.5690 | val 0.7076/1.2144 | best 0.7076 @ 240

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 241 | train 0.4150/1.5891 | val 0.5254/1.4807 | best 0.7076 @ 240

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 242 | train 0.4044/1.5821 | val 0.6886/1.2495 | best 0.7076 @ 240

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 243 | train 0.4325/1.5727 | val 0.7013/1.2557 | best 0.7076 @ 240

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 244 | train 0.4262/1.5741 | val 0.7352/1.1930 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 245 | train 0.3859/1.6452 | val 0.6780/1.2727 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 246 | train 0.4198/1.6035 | val 0.6483/1.3371 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 247 | train 0.3976/1.5796 | val 0.6907/1.2599 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 248 | train 0.4055/1.5281 | val 0.5572/1.4465 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 249 | train 0.3939/1.5741 | val 0.6589/1.2729 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 250 | train 0.4235/1.5531 | val 0.7097/1.2116 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 251 | train 0.3992/1.5372 | val 0.6589/1.3160 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 252 | train 0.4055/1.6181 | val 0.5890/1.3492 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 253 | train 0.4251/1.5903 | val 0.6843/1.2643 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 254 | train 0.4023/1.5856 | val 0.6356/1.3530 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 255 | train 0.4426/1.5267 | val 0.6610/1.2734 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 256 | train 0.5156/1.5345 | val 0.6292/1.3598 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 257 | train 0.4627/1.5011 | val 0.6992/1.2230 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 258 | train 0.3854/1.6076 | val 0.5869/1.4258 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 259 | train 0.4516/1.5695 | val 0.6483/1.3004 | best 0.7352 @ 244

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 260 | train 0.4272/1.5424 | val 0.7394/1.1869 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 261 | train 0.4468/1.5657 | val 0.7034/1.2196 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 262 | train 0.3949/1.5453 | val 0.6250/1.3581 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 263 | train 0.4182/1.5889 | val 0.5720/1.4280 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 264 | train 0.4463/1.5421 | val 0.7140/1.2087 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 265 | train 0.3923/1.5652 | val 0.5975/1.3581 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 266 | train 0.4992/1.5309 | val 0.4492/1.6267 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 267 | train 0.4611/1.4796 | val 0.6864/1.2576 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 268 | train 0.4648/1.4835 | val 0.6970/1.2214 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 269 | train 0.4865/1.4930 | val 0.6017/1.3784 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 270 | train 0.4590/1.5271 | val 0.5699/1.4184 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 271 | train 0.4468/1.5636 | val 0.5339/1.4898 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 272 | train 0.3880/1.5370 | val 0.6801/1.2895 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 273 | train 0.4309/1.5043 | val 0.6992/1.2641 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 274 | train 0.3896/1.5821 | val 0.7034/1.2380 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 275 | train 0.3949/1.5650 | val 0.7161/1.2129 | best 0.7394 @ 260

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 276 | train 0.4198/1.5683 | val 0.7585/1.1892 | best 0.7585 @ 276

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 277 | train 0.4177/1.5339 | val 0.6525/1.2787 | best 0.7585 @ 276

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 278 | train 0.4701/1.5312 | val 0.6165/1.3332 | best 0.7585 @ 276

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 279 | train 0.4352/1.5944 | val 0.7669/1.1390 | best 0.7669 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 280 | train 0.4479/1.5809 | val 0.7119/1.2474 | best 0.7669 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 281 | train 0.4791/1.4660 | val 0.7331/1.2159 | best 0.7669 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 282 | train 0.4542/1.5320 | val 0.7034/1.2954 | best 0.7669 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 283 | train 0.4717/1.5470 | val 0.7542/1.1663 | best 0.7669 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 284 | train 0.4780/1.5036 | val 0.6843/1.2438 | best 0.7669 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 285 | train 0.4537/1.5099 | val 0.6059/1.3523 | best 0.7669 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 286 | train 0.4134/1.5486 | val 0.6589/1.2849 | best 0.7669 @ 279

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 287 | train 0.3965/1.5021 | val 0.7797/1.1436 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 288 | train 0.4246/1.5193 | val 0.6758/1.2738 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 289 | train 0.4595/1.5289 | val 0.7436/1.1857 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 290 | train 0.4442/1.5974 | val 0.6653/1.2543 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 291 | train 0.4452/1.4529 | val 0.6843/1.2596 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 292 | train 0.4452/1.5741 | val 0.6462/1.3209 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 293 | train 0.4166/1.5946 | val 0.7140/1.2357 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 294 | train 0.4378/1.5640 | val 0.6928/1.2440 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 295 | train 0.4542/1.4993 | val 0.6568/1.2651 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 296 | train 0.4537/1.5047 | val 0.6674/1.2816 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 297 | train 0.3594/1.5412 | val 0.6843/1.2402 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 298 | train 0.4659/1.4745 | val 0.6886/1.2423 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 299 | train 0.4897/1.5098 | val 0.7479/1.1663 | best 0.7797 @ 287

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

seresnet50_bilinear_v3_patch_fold5 | ep 300 | train 0.4664/1.5544 | val 0.7373/1.1787 | best 0.7797 @ 287

SWA BN:   0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

SWA (106 snapshots) val acc: 0.7733  |  best ckpt: 0.7797
-> Keeping best checkpoint

  0%|          | 0/25 [00:00<?, ?it/s]

Saved: /home/onyxia/work/tilda-texture-classification/outputs/submissions/submission_seresnet50_bilinear_v3_patch_fold5_tta_labels0.csv
label
0    183
1     61
2     78
3     89
4     82
5     89
6     98
7    109
Name: count, dtype: int64
Saved: /home/onyxia/work/tilda-texture-classification/outputs/submissions/submission_seresnet50_bilinear_v3_patch_5fold_tta_labels0.csv
label
0    161
1     86
2    111
3     97
4     56
5     88
6    104
7     86
Name: count, dtype: int64

   fold  best_val_acc  best_epoch  training_time_min
0     1      0.845666         295         200.337123
1     2      0.758475         268         200.645059
2     3      0.796610         286         200.685333
3     4      0.764831         270         200.667881
4     5      0.779661         287         200.320507

Mean val acc: 0.7890 +/- 0.0349

## 12. Ensemble final — v1 + v2_patch + v2_full + v3

In [12]:
# Ensemble v3 + v1 + v2 (4 modeles)
v1_patch = np.load(CHECKPOINT_DIR / 'probs_seresnet50_bilinear_patch_v1_5fold.npy')
v2_patch = np.load(CHECKPOINT_DIR / 'probs_seresnet50_bilinear_v2_patch_5fold.npy')
v2_full  = np.load(CHECKPOINT_DIR / 'probs_seresnet50_bilinear_v2_full_5fold.npy')
v3_patch = np.load(CHECKPOINT_DIR / 'probs_seresnet50_bilinear_v3_patch_5fold.npy')
ids_ref  = np.load(CHECKPOINT_DIR / 'ids_seresnet50_bilinear_patch_v1_5fold.npy')

# Mega ensemble 4 modeles : poids egaux
mega4 = (v1_patch + v2_patch + v2_full + v3_patch) / 4.0
save_submission(ids_ref, mega4,
    SUBMISSION_DIR / 'submission_mega4_v1v2v3_labels0.csv')

# Avec v3 plus pondere (modele le plus recent)
mega4_v3boost = 0.20 * v1_patch + 0.20 * v2_patch + 0.20 * v2_full + 0.40 * v3_patch
save_submission(ids_ref, mega4_v3boost,
    SUBMISSION_DIR / 'submission_mega4_v3boost_labels0.csv')

Saved: /home/onyxia/work/tilda-texture-classification/outputs/submissions/submission_mega4_v1v2v3_labels0.csv
label
0    132
1     89
2    100
3     97
4     89
5     91
6     98
7     93
Name: count, dtype: int64
Saved: /home/onyxia/work/tilda-texture-classification/outputs/submissions/submission_mega4_v3boost_labels0.csv
label
0    137
1     89
2    103
3     96
4     86
5     91
6     98
7     89
Name: count, dtype: int64

      id  label
0      1      3
1      2      4
2      3      4
3      4      0
4      5      2
..   ...    ...
784  785      1
785  786      0
786  787      7
787  788      2
788  789      5

[789 rows x 2 columns]